### ISSUE TITLE
Question Planing?

### ISSUE THREAD

**Issue by Droppix** [parse-community/parse-server#3701]
Hi,

Do you have a development plan in the coming weeks / months? Because from the outside, one has the impression that development has stopped!

Best regards

**Comment by flovilmart** [comment]
We don't hold a development plan, but we're fully commited to maintain and evolve parse-server.

also I'm not sure why you'd say the développement has stopped. Pull requests are merged on a daily basis, issues are usually answered  and solved within a day as well.

Are there features or bugs you have in mind thar require particular attention?

**Comment by Droppix** [comment]
Thanks for your response.

I have been following you since january 2016, and I have seen frequent updates, which answered a lot of bugs / evolutions, but for some time I have the impression that there is no evolution (cf: Cloud Code in Dashboard, Folders in PFFile, Purge file in GridFS...).
For this reason, I think that from a developer point of view, it would be interesting to have a view on the next releases ...

**Comment by flovilmart** [comment]
it's not because those features are not high priority that we don't actively work on evolving the tools.

And those particular features have been heavily discussed and I encourage you to work on them.

An open source community doesn't mean a few maintainers implement all the requested features. It means every single user has the ability to provide meaningful changes to the code base to help tailor it for their needs. 

Also, not sure you've noticed by I spend the last 12 hours making sure all the docs don't have broken links or images, which is, far more important in my eyes than implementing a code viewer in the dashboard.

**Comment by natanrolnik** [comment]
Closing this issue, filing under "reasons why open source might not work". Unconstructive criticism that doesn't help much, and depreciates [all the recent work](https://github.com/parse-community/parse-server/commits/master).

As @flovilmart said, you could help making Parse Server/Dashboad with issues triage, helping others, opening PRs and helping with suggestions/discussions, instead of only opening issues as a free Support Channel [when you need help](https://github.com/parse-community/parse-server/issues?utf8=✓&q=is%3Aissue%20author%3ADroppix).
