### ISSUE TITLE
How to use master key in .Net (not on cloud code, needed on local code)

### ISSUE THREAD

**Issue by saikiran644** [parse-community/parse-server#3702]
I'm trying on some code where the data should be fetched irrespective of ACL (like using a master key). But I couldn't find it in .Net (where to include). Please help with the issue.

**Comment by natanrolnik** [comment]
The best is to create a Cloud function, and call your function from the .Net client. Inside that function, you set `{useMasterKey: true}` as the options for the query.

**Comment by saikiran644** [comment]
@natanrolnik Thank you so much for the reply. :+1: 
But I don't want to do it in a cloud function (I don't want to use limited cloud jobs for this) , instead from the local code itself. Is there any such option to do it that way?

**Comment by flovilmart** [comment]
We don't allow masterKeys in the clients for security reasons, as any user would have full control over you parse deployment

**Comment by natanrolnik** [comment]
@saikiran644 you don't need a Cloud Jobs for this. A simple `Parse.Cloud.define("YourFunction", function(req, res) {}` with the correct code inside will be enough. Only perform the query from the cloud function in JS, instead of doing it in .Net. And Cloud Jobs or Functions are not limited in any way.

**Comment by saikiran644** [comment]
Thank You @natanrolnik  & @flovilmart :+1:
