### ISSUE TITLE
Can't send push to iOS device from Cloud Code

### ISSUE THREAD

**Issue by wellkeptbeauty** [parse-community/parse-server#3794]
server config on index.js file

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodburi',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'appid',
  masterKey: process.env.MASTER_KEY || 'masterkey, //Add your master key here. Keep it secret!,
 // clientKey:process.env.CLIENT_KEY || 'cleintkey', //Add you client key here. Keep it secret!,
  fileKey:process.env.FILE_KEY || 'filekey', // Add you file key here,
  serverURL: process.env.SERVER_URL || 'https://appname.herokuapp.com/parse',  // Don't forget to change to https if needed
  push: {
  ios: [
    {
      pfx:__dirname + '/certificates/pushfordevelopment.p12',
      bundleId: 'com.appname',
      production: false
    }
  ]
}, 
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
   push: JSON.parse(process.env.PARSE_SERVER_PUSH || "{}"),
});

my cloud code

Parse.Cloud.define("iosPushforsingleuser", function(request, response) {
	
	var query = new Parse.Query(Parse.User);

  query.equalTo('username', 'emailid');
	

  // here you can add other conditions e.g. to send a push to sepcific users or channel etc.

  var payload = {
    alert: "testing",
	  sound: "",
            'content-available': 1
      // you can add other stuff here...
  };

  Parse.Push.send({
      data: payload,
      where: query
    }, {
      useMasterKey: true
    })
    .then(function() {
      response.success("Push Sent!");
    }, function(error) {
      response.error("Error while trying to send push " + error.message);
    });
});

push status on mlab

{
    "_id": "7khYdx0LKs",
    "pushTime": "2017-05-09T06:33:37.275Z",
    "query": "{\"username\":\"xxx@xxx.com\"}",
    "payload": "{\"alert\":\"YOUR_MESSAGE\",\"sound\":\"\",\"content-available\":1}",
    "source": "rest",
    "status": "succeeded",
    "numSent": 0,
    "pushHash": "5a5228294bd8cd3aeb836d9834da9152",
    "_wperm": [],
    "_rperm": [],
    "_acl": {},
    "_created_at": {
        "$date": "2017-05-09T06:33:37.275Z"
    },
    "_updated_at": {
        "$date": "2017-05-09T06:33:37.304Z"
    },
    "numFailed": 0
}

**Comment by natanrolnik** [comment]
Hey @wellkeptbeauty. A few notes:

Please format better your cloud code. For help with Markdown, [check this link.](https://guides.github.com/features/mastering-markdown/)
**Never, ever, post anyone of the following on the web:**

- Database address, user and password;
- Master Key (it should really be a secret!)
- Push certificates

You have all of them in your `parseserverforwellkeptbeauty` - make the repo private, or delete the project from GitHub. You should [use environment variables](https://devcenter.heroku.com/articles/config-vars) instead of keeping them in plain text. Deleting these lines won't help, as git keeps the commit history.
