### ISSUE TITLE
How to store parse object with parse user locally

### ISSUE THREAD

**Issue by gate3** [parse-community/parse-server#3871]
Hi, I would like to know if its possible to store an object from another class that isn't the _User class locally along with the _User class. If It's not possible, what recommendations are there for the type of local DB to use to store parse server objects? Thank you

**Comment by natanrolnik** [comment]
Hi @gate3 

I'm closing this issue because we use GitHub issues only for bug reporting. Questions like this are more suitable for StackOverflow. Please ask there and post the link here.

Additionally, I recommend you to read the docs. Check the following sections:

* Relational data: [iOS](http://docs.parseplatform.org/ios/guide/#relational-data) & [Android](http://docs.parseplatform.org/android/guide/#relational-data)
* Local Datastore: [iOS](http://docs.parseplatform.org/ios/guide/#local-datastore) & [Android](http://docs.parseplatform.org/android/guide/#local-datastore)
