### ISSUE TITLE
[PROPOSAL/DISCUSSION] Neo4J Graph Database support

### ISSUE THREAD

**Issue by markmssd** [parse-community/parse-server#3938]
It sadness me having to move away from Parse Server to be able to use Neo4J, so I was thinking of making an adapter `parse-server-neo4j-adapter` to support it. If there is enough interest (and if it's even possible, of course), I would be happy to start implementing it.

The only concern I have is about Files storage. As per their thread [here](https://neo4j.com/blog/dark-side-neo4j-worst-practices), it's a very bad idea to try storing files on it. MongoDB natively supports GridFS, but in the case of Neo4J, I believe it would be required to use it with another File Storage adapter, such as Amazon S3.

What are your thoughts?

**Comment by flovilmart** [comment]
That would be very nice, the main question is the scope that neo4j supports compared to mongo in terms of storage flexibility, we made it work on postgres, so I don't see any major roadblocks.

As per the storage, that's 100% fine if not supported by neo4j

**Comment by dplewis** [comment]
@flovilmart I'm thinking about doing a DB adapter. Is there a checklist of mongo functionality? A check list would provide a quick reference without going through the adapter. Maybe the next roadmap would be adding adapters.

**Comment by flovilmart** [comment]
That's quite tricky to do a full checklist, the best source would be the rest documentation. Then in terms of interface, the DB adapters are well defined and the Pg adapter, being contained in a single file, would be the way to go.
Something that would be possible is a full spec that solely tests the DB adapters for compatibility. That would be quite nice to write but edge cases are also tricky to cover.

**Comment by dplewis** [comment]
The test suite is like a checklist I guess.

> full spec that solely test the DB adapter for compatibility

What would that look like?

**Comment by flovilmart** [comment]
That would be the basic CRUD operations for the DB for all data types, this is quite well définied and everything that comes in is in the Parse REST format and anything that gets out should be in the REST format as well. 

I guess the 1st step would be to design a spec that yields 100% coverage of the PG adapter (and only the PG)

**Comment by flovilmart** [comment]
Also in the parse-server-modules org we have the parse-server-conformance tests repo that was initially setup to run tests against any files adapter, we could very well draw some inspiration there

**Comment by dplewis** [comment]
If you can create a skeleton and structure. I'll work in it.

**Comment by flovilmart** [comment]
yeah that's easier said than done :) I believe I could get started on an external repo so the coverage is not polluted by the currently running tests. as you can see [here for mongo](https://codecov.io/gh/parse-community/parse-server/tree/master/src/Adapters/Storage/Mongo) and [here for postgres](https://codecov.io/gh/parse-community/parse-server/tree/master/src/Adapters/Storage/Postgres) the coverage is pretty high, because of the complexity of the test suite, the goal would be to reduce to the 'bare metal' tests for the facade of those adapters, which can get quite overwhelming. 

I'll see what I can do to get started.

**Comment by dplewis** [comment]
> yeah that's easier said than done

I knew you were going to say that :)

**Comment by flovilmart** [comment]
we leverage some PG specific features like json, arrays and geo points, I'm not sure to which extent those are supported in PG.

**Comment by dplewis** [comment]
The latest version of MySQL supports json. Geopoints are supported. Arrays aren't but they can be serialized as strings

**Comment by flovilmart** [comment]
Seems promising then!

**Comment by dplewis** [comment]
I'll start on a separate repo for that while you do adapter specs

**Comment by flovilmart** [comment]
The adapter specs will take a while but I can get started on them.

**Comment by dplewis** [comment]
Sounds good. I have nothing to do over the summer so I'm free to help out anyway I can

**Comment by dplewis** [comment]
@markmssd I never heard of Neo4J before but it looks awesome. What are some of the benefits of Neo4J, I might use it some day.

**Comment by markmssd** [comment]
There's well detailed examples of use cases on their website [here](https://neo4j.com/use-cases).

For my case, I need it to build a highly connected graph of waypoints, and find the shortest path between the nodes (will use Cloud Code for that specific case). I did a quick backend draft to play with it and it's really easy to grasp and use, especially with their Cypher language!

I will familiarize more with it before starting a Parse Server adapter

**Comment by whitelizard** [comment]
Hello,
Has there been any progress in this direction?

From my perspective, a connection to OrientDB would be really interesting!

**Comment by mtrezza** [comment]
It is unlikely that there will be supported database adapters beyond MongoDB and Postgres that are fit for production environment. A database adapter requires a lot of effort because it sits between the database and Parse Server, both of which are continuously evolving and therefore requiring updating to provide the stability expected in a production environment. Without a group of maintainers that keep the adapter updated, it will become unusable quite quickly, we can see the challenge for maintaining the Postgres adapter, which is chronically behind the MongoDB adapter in terms of features and to this day lacking some features.

In addition, this thread is 4 years old and Parse Server has evolved significantly in terms of features and supported queries, such as geo-queries, so the entry barrier for new adapters is even higher.

If you feel strongly about introducing a new database adapter, I suggest to first find a group of likeminded developers who would join you in the effort of initial development and continuous maintenance of the adapter.

**Comment by sahilpohare** [comment]
Well this is sad.
My use case extensively uses Neo4j. I love parse server and do not wanna move away from it and the high flexibility it offers. 
Can you suggest a way to integrate Neo4j in current state of Parse? Maybe a dual database streaming new data to neo4j with webhooks?
