### ISSUE TITLE
How can know how many users not facebook's user?

### ISSUE THREAD

**Issue by uluru-phatnguyen** [parse-community/parse-server#3946]
I do not know why can not use doesNotExist('authData') to check user in Parse.Query

I wrote code:
`
const fbQuery = new Parse.Query(Parse.User);
fbQuery.doesNotExist('authData');
fbQuery.count().then((num) => {
     console.log(num);  
});
`
Result: alway 0.

I checked data on database via parse-dashboard, I saw authdata of facebook account.

Pls help me.

Thank you so much.

**Comment by pungme** [comment]
Have you tried useMasterKey option?

**Comment by natanrolnik** [comment]
Probably @pungme is right. But remember that `authdata` might be related to other authentication methods, like Twitter, Instagram, etc...

I'm closing this issue because we try to keep GitHub issues for issues and bugs specific of Parse Server.

Please use StackOverflow with the parse-server and parse-js-sdk tags, and post the link here for reference as well.

**Comment by uluru-phatnguyen** [comment]
@pungme  @natanrolnik 
have you checked?

I also checked with masterKey but not work.

**Comment by pungme** [comment]
@uluru-phatnguyen can you create question on stack overflow? Thanks!
