### ISSUE TITLE
LiveQuery Disconect Event

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [parse-community/parse-server#3951]
Hello,

Thanks to all the great contributors out there working to make this piece of software great...

I have an issue with LiveQuery I would like to use the disconect event to set user account to ofline status but there is no where in the documentation or any relevant material available to explain how I can make this happen  

Example: when the system log "info: Client disconnect: value " I would like to know for whom it has log that event to set its account to a different state like offline.

**Comment by flovilmart** [comment]
You should probably have a flag on the user connection start (online/offline) OR a table (OnlineUser) and you would make a subscription to that table in order to know what user is connected or not. What you're suggesting would not work with the current architecture of parse-server and LiveQuery client.

**Comment by THEDOWNCOUNTRY** [comment]
I am in the same situation where we trying to know to whom the disconect event is.
