### ISSUE TITLE
localhost:1337/parse {"error":"unauthorized"} 

### ISSUE THREAD

**Issue by Crazyfirethe13** [parse-community/parse-server#3972]
i followed this tutorial https://www.youtube.com/watch?v=o522ovITvW4&t=671s and did mostly what it did (besides some issue i had to fix myself) but only http://localhost:4040 works while http://localhost:1337/parse has {"error":"unauthorized"}  (can provide any info on request)

**Comment by natanrolnik** [comment]
Hi @Crazyfirethe13. 
It seems that this is the same issue as #3967 that you opened earlier, right?

In order to help, contributors need a minimal amount of information, and this is why we have the issue template. It’s not there to be ignored and deleted, but to help the author of the issue what information is needed. Sample code (formatted, if possible), is also welcome. 

Which port did you initialize your server? Which keys did you configure your parse-server with?
