### ISSUE TITLE
APNS bundleId is deprecated

### ISSUE THREAD

**Issue by adirgan** [parse-community/parse-server#3987]
### Issue Description

In the last version of parse-server 2.5.2, when sending push messages to an iOS device the following message appears, I would like to know what the new configuration is used.

Push: {
     Android: {
       SenderId: '', // The Sender ID of GCM
       ApiKey: '' // The Server API Key of GCM
     },
       Ios
       {
         Pfx: '/root/prod.p12',
         BundleId: 'com.apple',
         Production: true
       },
       {
         Pfx: '/root/dev.p12',
         BundleId: 'com.apple',
         Production: false
       }
     ]
   }

The error is:

**WARN parse-server-push-adapter APNS bundleId is deprecated, use topic instead**

How will the new configuration for the iOS push?

### Steps to reproduce

Send a push to iOS Device with the parse-server 2.5.2 with the old configuration with `bundleId`.

#### Expected Results

Not Warn

#### Actual Outcome

WARN parse-server-push-adapter APNS bundleId is deprecated, use topic instead

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.2
  - Operating System:    Ubuntu
  - Hardware:            VPS 8 Core 8 Gb Ram
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): 

### Logs/Trace

1|RTC      | WARN parse-server-push-adapter APNS bundleId is deprecated, use topic instead

**Comment by natanrolnik** [comment]
Hey @adirgan thanks for your report.

Yes, this changes were introduced with the 2.0.0 release of [parse-server-push-adapter](https://github.com/parse-server-modules/parse-server-push-adapter), in [these lines](https://github.com/parse-server-modules/parse-server-push-adapter/blob/02bfda8c78f783a5bf8d4562fcafd15c9ef577c6/src/APNS.js#L44-L48). 

I wanted to invite @flovilmart and @Schwobaland for the discussion. We have two options ahead:

**1**: We keep the backwards compatibility warning and update the docs to match the push adapter behavior (meaning, we recommend the usage of `topic` instead of `bundleId`).

**2**: We remove the warning, and make the adapter work just as fine with `bundleId`. Passing `topic`, or passing `topic` **and** `bundleId`, in the other hand, is discouraged and triggers the warning, in order to keep the consistency between adapters.

I think we should go with the second option. In my opinion, the adapter's responsibility is to **adapt**  parse-server to the push sending code. No matter which adapter I choose for iOS, I should pass always the same parameters.

What do you guys think?

**Comment by flovilmart** [comment]
@natanrolnik, the push initialization is a mess, and historically a mess as it started baked into Parse server. What happens under the hood, is that the push options is passed to the ParseServerPushAdapter and the adapter validates it. 

The initialization API can’t be the same for all push adapters, for ex, AWS SNS needs different Parms etc... we’re gonna stick with 1 and fully deprecate bundleID at a later date as this semantic doesn’t match with the APNS 2 protocol semantics.

**Comment by natanrolnik** [comment]
I'm fine with it - we need to update the docs then.

**Comment by flovilmart** [comment]
Probably yes ;)

**Comment by adirgan** [comment]
@flovilmart The question is if the topic is the same parameter as BundleID

**Comment by natanrolnik** [comment]
@adirgan yes, it is. You can read this from the warning itself: 

> `bundleId` is deprecated, use `topic` instead

**Comment by manishsangwan** [comment]
@flovilmart i couldn't find the docs showing how to configure topic .Push notification configuration docs only shows bundle id usage  http://docs.parseplatform.org/parse-server/guide/#push-notifications. Where can i find docs using topic instead of bundle id.

**Comment by flovilmart** [comment]
That’s the same, just replace the key bundleID by topic
