### ISSUE TITLE
Error on query in beforeSave/afterSave/define

### ISSUE THREAD

**Issue by alejonext** [parse-community/parse-server#4010]
The error is as follows when executing a query within Cloud in 'main.js'. This sends an internal request, here are generated two problems

- The first one if it is doing debug, it looks perfectly what is sent however it is in an override
 method in '_method'. When doing this, the "Parser-server" does not decode the override, and a failure is generated, or in case the logic in Express follows.
- When run without debug, this looks for the XMLHttpRequest. NodeJS, does not support such methods.

### Steps to reproduce
Create a class with any data...

in cloud/main.js
```
Parse.Cloud.beforeSave(Parse.User, function(req, res){
	(new Parse.Query(Parse.Object.extend('COOL_DATA')))
		.get('My_ID_COOL_DATA', vars.MASTER_KEY)
		.then((data) => {
			req.object.set('yourCoolData', data.get('anyData'));
			res.success();
		})
		.catch((e) =>{
			console.log('error', e);
			res.error(e);
		});
});
```
in server.js
```javascript
server.use(vhost(`api.${global.CONFIG.server.domain}`,  new ParseServer(
  cloud : 'cloud/main.js',
  serverURL : `http://api.${global.CONFIG.server.domain}/`, // Is local with subdomains
  publicServerURL : `http://api.${global.CONFIG.server.domain}/`,
  appId: 'myApp'
  appName: 'My App'
  databaseURI: '...',
  verbose: true,
  masterKey: 'a'
  javascriptKey: 'j'
  restAPIKey: 's'
  clientKey: 'T'
)));
server.listen(...)
```
And... run
```
$ node-debug server.js
```
All is LOCAL

#### Expected Results

Both the query or the obtaining of the object are expected as well as saving the user.

#### Actual Outcome

```
{
    "code": 141,
    "error": {
        "code": 100,
        "message": "XMLHttpRequest failed: \"Unable to connect to the Parse API\""
    }
}
```

### Environment Setup

- **Server**
  - parse-server version  : 2.5.3
  - Operating System       : Mac Sierra
  - Localhost with Hotel

- **Database**
  - MongoDB version: 3.4.4
  - Localhost

### Logs/Trace

```
verbose: REQUEST for [POST] /users: {
"username": "cooldude6",
"password": "********",
"phone": "415-392-0202"
} method=POST, url=/users, accept-language=es-419,es;q=0.8, accept-encoding=gzip, deflate, referer=http://myApp.dev/dash/apps/Non%20Liquet/api_console, accept=*/*, content-type=text/plain;charset=UTF-8, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36, x-parse-master-key=a, x-parse-application-id=myApp, origin=http://myApp.dev, content-length=69, proxy-connection=keep-alive, host=api.myApp.dev, connection=close, username=cooldude6, password=********, phone=415-392-0202
User ParseUser { _objCount: 4, className: '_User' }
error ParseError {
code: 100,
message: 'XMLHttpRequest failed: "Unable to connect to the Parse API"' }
error: beforeSave failed for _User for user undefined:
Input: {"username":"cooldude6","password":"********","phone":"415-392-0202"}
Error: {"code":141,"message":{"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}} className=_User, triggerType=beforeSave, code=141, code=100, message=XMLHttpRequest failed: "Unable to connect to the Parse API", user=undefined
error: Error generating response. ParseError {
code: 141,
message:
ParseError {
code: 100,
message: 'XMLHttpRequest failed: "Unable to connect to the Parse API"' } } code=141, code=100, message=XMLHttpRequest failed: "Unable to connect to the Parse API"
```

**Comment by flovilmart** [comment]
not sure if it's not a copy/paste error but your serverURL and publicServerURL are invalid (hptt instead of http).

Also, serverURL should be in the form `http://localhost:<PORT>/<mountPath>` and not the public form.

**Comment by alejonext** [comment]
@flovilmart well i use [hotel](https://github.com/typicode/hotel) you create a multiple domains for dev, in your local...

**Comment by flovilmart** [comment]
That's unrelated, the serverURL should not be the public one, if the XMLhttpRequest fails, it means the http server is unreachable, which points to serverURL being invalid.

**Comment by jbschaff** [comment]
@alejonext I'm receiving a similar error and have set the serverURL to what @flovilmart mentioned. It's related to a variable initialization but haven't figured it out yet. Does your parse dashboard show in the column for that table? I have a pointer for 'user' in the Installation table and it says (undefined). 

Logs: `error: Error generating response. TypeError: Cannot read property 'get' of undefined`

**Comment by developerX** [comment]
I am having a similar issue, I just set up a new react native app and want to use parse server with my build. I am trying to do a simple user signup but the error response : `{ code: 100, message: 'XMLHttpRequest failed: "Unable to connect to the Parse API"' }`

I am running parse server locally, I can hit the end points with my REST client. I have tried many solutions but nothing seems to work? 

Any ideas? @flovilmart

**Comment by flovilmart** [comment]
@developerX how is your server URL configured.
@jbschaff where do you see the issue.
@alejonext I'M not familiar with hotel, but you should probably investigate the configuration passed to the server and make sure the serverURL is valid.

**Comment by jbschaff** [comment]
@flovilmart @alejonext @developerX thanks for following up. I was able to send a test notification through cloud code function by setting Heroku SERVER_URL to: `https://xxxxxxxx.herokuapp.com/parse` and had to modify index.js with: `var https = require('https');` and `Parse.serverURL = process.env.SERVER_URL;` before `var api = new ParseServer({`. Also set `serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',`. 

Cloud code function that sent test push notification: 

`Parse.Cloud.define("iosPushTest", function (request, response) {
  var params = request.params;
  var user = request.user;
  var messageText = params.text;

// Set our installation query
  var pushQuery = new Parse.Query(Parse.Installation);
   pushQuery.equalTo('deviceType', 'ios');
   console.log(pushQuery);

  // Send push notification to query
  Parse.Push.send({
    where: pushQuery,
    data: {
      alert: "Message: " + messageText
      } 
        }, { useMasterKey: true })
    .then(function() {
      // Push sent!
      console.log("push sent!");
    }, function(error) {
      // There was a problem :(
      console.error(error);
    });
response.success('success, end of iosPushTest')
});`

Now I'm attempting to send a notification to all followers of a user. Still not able to query a user pointer in the installation table because it's not initializing with a value. I receive the error on the line ` query.equalTo("objectId", request.object.get("user").id); `. Here's the modified function returning an error: 

`Parse.Cloud.define("iosPushTest", function (request, response) {
  var params = request.params;
  var user = request.user;
  var messageText = params.text;

var query = new Parse.Query(Parse.User);
        query.equalTo("objectId", request.object.get("user").id);   **// undefined** 
        query.first({ useMasterKey: true }).then(function(userRetrieved) {  
                console.log(displayTime() + ' - User Retrieved  - name :' + userRetrieved.get("firstName"));
                console.log(displayTime() + " - Installation Id is: " + request.object.get("installationId"));

            var pushQuery = new Parse.Query(Parse.Installation);
            pushQuery.equalTo('deviceType', 'ios');                                                                                                                                          
            pushQuery.equalTo('user', userRetrieved); 
            pushQuery.equalTo('installationId', userRetrieved.get("installationId"));
            console.log("Inside finished query, push next" + user);
            
           Parse.Push.send({
           where: pushQuery,
           data: {
                    alert: messageText
          } 
          }, { useMasterKey: true })
         .then(function() {
      // Push sent!
         console.log("push sent!");
         }, function(error) {
      // There was a problem :(
       console.error(error);
    });
response.success('success, end of iosPushTest')
});`

Parse Dashboard is showing: 

<img width="1118" alt="screenshot 2017-07-25 20 18 38" src="https://user-images.githubusercontent.com/2449438/28600639-cad10f0e-7178-11e7-9791-73fd72c3fb7f.png">


I apologize in advance if I'm not clearly/correctly describing the issue -- just started learning a few months ago.

**Comment by flovilmart** [comment]
Closing for now, please update parse-server to the latest version and make sure to fill a new issue report if it persists.
