### ISSUE TITLE
iMessage extension crashes because Parse is initialised twice

### ISSUE THREAD

**Issue by AlbinGrans** [parse-community/parse-server#4011]
### Issue Description

We are developing an iMessage extension with Swift. And to be able to initialize Parse, we have the put the Parse initialize code inside any of the iMessage controllers. Whenever a controller reopens, the app crashes. We have tried to put both in the override init and viewDidLoad.

### Steps to reproduce
Code in viewDidLoad or override init:
```
Parse.initialize(with: ParseClientConfiguration(block: { (configuration: ParseMutableClientConfiguration) -> Void in
            
            configuration.server = "https://xxxxx.io/parse/"
            configuration.applicationId = "xxxxxxx"
            
        }))
```

Then I run the app, and if I present a new controller it crashes with the error message in xcode:
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Parse is already initialized.'`
#### Expected Results

Parse connecting to the server with no errors.
#### Actual Outcome

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Parse is already initialized.'`

### Environment Setup

- **Server**
  - parse-server version 1.15.0
  - Operating System:    macOS Sierra
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: v3.4.5
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

**Comment by natanrolnik** [comment]
We keep this repo's issues only for tracking bugs on Parse-Server, the node.js package designated for server side.

Please open this issue in the relevant repo - https://github.com/parse-community/Parse-SDK-iOS-OSX/issues

A few suggestions 
- Don't do the Parse initialization in `viewDidLoad` 
- Add some breakpoints to check who is initializing Parse for the first time before this one
- In case you think it might be already initialized, call `Parse.getApplicationId()` before in order to see if it's set or not.
