### ISSUE TITLE
PFFile crashes with larger than 10mb

### ISSUE THREAD

**Issue by neilgandhi95** [parse-community/parse-server#4031]
When I try to upload files greater than 10mb to my parse server, I get an error on the client side saying

    Error Domain=NSCocoaErrorDomain Code=263 "Failed to create PFFile at path '/var/mobile/Containers/Data/Application/voice_message.mp4': file is larger than 10MB." UserInfo={NSLocalizedDescription=Failed to create PFFile at path '/var/mobile/Containers/Data/Application/voice_message.mp4': file is larger than 10MB.}

What's the best way of going about this? Should I split the file up into multiple PFFiles, upload that, and then restitch them on the server? Should I even use PFFile? Any advice would be super appreciated!

Cheers!

**Comment by montymxb** [comment]
@neilgandhi95 This looks like an issue for the [iOS sdk](https://github.com/parse-community/Parse-SDK-iOS-OSX), especially with the fact the error indicates an issue with saving in a local `/var...` directory.

With that in mind I would personally set a limit on the file size that you can generate, since it looks like there is definitely a limit there. I'm going to go ahead and close this since this isn't the right location, but be sure to open up the issue over there instead to wrap this up.
