### ISSUE TITLE
NPM Install report error.

### ISSUE THREAD

**Issue by kevinlee85** [parse-community/parse-server#4036]
We use GitHub Issues for bugs.

If you have a non-bug question, ask on Stack Overflow or Server Fault: 
- https://stackoverflow.com/questions/tagged/parse.com 
- https://serverfault.com/tags/parse

You may also search through existing issues before opening a new one: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue 

--- Please use this template. If you don't use this template, your issue may be closed without comment. ---

### Issue Description

I am trying to run the parse server within my owner MAC.
Then I cloned the least code, then run npm install to download and setup all necessory dependence libraries.
Then the npm report error like below:
`npm ERR! code EINTEGRITY
npm ERR! sha1-DCi8ZpqFFiFwm/eghQMDS+44ErY= integrity checksum failed when using sha1: wanted sha1-DCi8ZpqFFiFwm/eghQMDS+44ErY= but got sha1-EfIhLjKFhqRwaWJpXrasiaOOKsM=. (513235 bytes)`

My node version is  v8.2.1
My npm version is v5.3.1
### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

#### Expected Results

What you expected to happen.

#### Actual Outcome

What is happening instead.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by montymxb** [comment]
If you have an **package-lock.json** I would try deleting it and running `npm install` again. If it still persists I would try clearing the cache via `npm cache clean --force` and remove **node_modules**, and try installing again.

If, after that you're _still_ bugged you may want to consider checking to upgrade npm or reinstalling it altogether. It appears that this is a [bug in npm itself](https://github.com/npm/npm/issues/16861), rather than parse-server. So I'll go ahead and close this, but multiple solutions have been posted over there, I would double check all of those and hopefully you can work it out!
