### ISSUE TITLE
Parse Server doesn't send email verification for OAuth logins

### ISSUE THREAD

**Issue by madsb** [parse-community/parse-server#4041]
Regarding #2660 and #3882, no email verifications are currently sent if the user is authenticated using OAuth - but this is a problem with for example Account Kit, which authenticates via mobile phone.

My login flow is currently passwordles: User can log in with either Facebook or Account Kit. If she logs in with Facebook, I get the email from there, and the user should not get a verification email (which #3882 takes care of).

But if the user logs in with Account Kit in my app, she must enter her email the first time she logs in - and the email verification should be triggered. If she changes her email after logging in with either Facebook or Account Kit, the email verification should also be triggered.

I've currently hacked it for my use case by changing line 459 in RestWrite.js to:

`if (!_this8.data.authData || !Object.keys(_this8.data.authData).length || Object.keys(_this8.data.authData).length === 1 && (Object.keys(_this8.data.authData)[0] === 'anonymous' || Object.keys(_this8.data.authData)[0] === 'accountkit')) {`

... but it's not exactly something I would put in a pull request 😆 Also, that hack doesn't take care of the "user logs in with Facebook and changes email afterwards" use case.

**Comment by flovilmart** [comment]
Thanks for reopening the issue, we’ll have a look :) one strategy would be to rip-off that code and infer the need from sending the verification email from another way.

**Comment by flovilmart** [comment]
@madsb actually, we added this issue on purpose, as users were complaining that emails were sent part of the login with facebook for example (#3882) I'm not sure what to do... Any suggestion

**Comment by madsb** [comment]
I took a look at it when encountering the issue, but wasn't confident with a more thorough solution than the hack I made myself.

I'd personally rather revert to the old way, although it results in an email confirmation when logging in with Facebook. The main problem with the current solution is (apart from my issue with Account Kit) that if the user logs in with Facebook and is permitted to change his email, an email verification request is not sent out.

**Comment by ferrinho** [comment]
Hi, I'm having the exact same problem you mentioned: not sending verification email on facebook login, works fine for me. But the problem is that if user changes his email, I need to send confirmation email, which is not working... If I trigger it as instructed in #3543 , I do receive the verification email, but I get "invalid link" as it appears the token=undefined. 

Any suggestions or workaround for this? Thanks a lot.

**Comment by flovilmart** [comment]
We could probably add a an options somewhere that would let the developer decide wether an email should be sent for verifying the newly set email adress. By default, the behavior would be the same as the current one. Perhaps verifyUserEmails could support a function instead of a Boolean, this function should return a Boolean, to tell the server wether the verification email should be sent.

What do you think @madsb @ferrinho? 

On your case @ferrinho, this requires more investigation.

**Comment by ferrinho** [comment]
I think that's a great idea @flovilmart , but in my case, I would always need to send verification email when a new one is set, no matter what the authentication method is. 

For now, would you suggest any workaround/hack to achieve this?

**Comment by flovilmart** [comment]
This would require those changes, unfortunately. I’ll provide as much context as possible for this method so you’ll be able to infer when to send it.

**Comment by REPTILEHAUS** [comment]
@flovilmart @madsb @ferrinho Im encountering this issue myself now and notice this bug was closed as stale, was it ever rectified ?

**Comment by Danaru87** [comment]
We have similar problem:

- We connect our user with Facebook
- We get the associated email from Facebook
- We update user with this email

Result:
- The user has emailVerified at "false"
- Email verification is triggered, an email is received by the user.

We tried to force user emailVerified to true with masterKey but does not work.
