### ISSUE TITLE
How to send push notification on a single device?

### ISSUE THREAD

**Issue by xicom** [parse-community/parse-server#4042]
I am using cloud function like 
Parse.Cloud.define("iosPush", function(request, response) {

    var user = request.user;
    var params = request.params;
    var someKey = params.someKey
    var data = params.data

    var pushQuery = new Parse.Query(Parse.Installation);
    pushQuery.equalTo('deviceType', 'ios'); // targeting iOS devices only
    pushQuery.equalTo("someKey", someKey)

    Parse.Push.send({
        where: pushQuery, // Set our Installation query
        data: data
    }, { success: function() {
        console.log("#### PUSH OK");
    }, error: function(error) {
        console.log("#### PUSH ERROR" + error.message);
    }, useMasterKey: true});

    response.success('success');
});

For all IOS users. But when I use this function, the push sent to the all devices.
How can we send the push on a specific device? We are using mongodb having users document.
Can you please help?

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by xicom** [comment]
I am sorry.. I have posted it now https://stackoverflow.com/questions/45279222/send-a-push-notification-on-a-single-device-through-heroku-parse-server
Can you please reply on this.
