### ISSUE TITLE
Question - Paginating GeoQueries

### ISSUE THREAD

**Issue by otymartin** [parse-community/parse-server#4075]
@dplewis @flovilmart 
This is more of a question/Discusion.

I'm curious whats the best way to go about paginating a geoquery given the following scenario.
I want to retrieve users within a max 10km radius of the the currentUser's location ordered from closest to furthest with a limit of 12 results at a time. 

Here is my current query. The problem is that it doesnt account for movement among users so it ends up skipping people. Would love for some ideas for a more intelligent query.
This article provided some answers however would like to here some opinion from people here.
https://emptysqua.re/blog/paging-geo-mongodb/

```swift
        let query = PFUser.query()
        query?.limit = 12
        query?.addAscendingOrder(UserKey.location)
        query?.skip = self.people.count ?? 12
        query?.whereKey(location, nearGeoPoint: currentUserLocation, withinKilometers: 10)
```

- **Server**
  - parse-server version  : 2.5.3
  - Localhost or remote server? Google App Engine

- **Database**
  - Localhost or remote server? mLab

**Comment by bohemima** [comment]
Instead of skip, couldn't you simply combine with `notContainedIn([already, seen, objectIds])`

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
