### ISSUE TITLE
Patent Issue

### ISSUE THREAD

**Issue by joielechong** [parse-community/parse-server#4108]
I'm reading https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2 over React.js  BSD+Patent license and found that the parse-server is using the same patent clause. How do you guys think about this issue?

**Comment by flovilmart** [comment]
In our case, the project is not maintained by Facebook anymore, i’ll Check what stands for the licence. As mentioned, the code has been transferred to the github organization, so you should probably be safe. I’ll update as more information comes in.

**Comment by nbering** [comment]
As I understand it, if you want to change the license you would need to contact all past contributors to get their permission to change it. That is unless you have a Contributor's License Agreement that says otherwise. You'd need consensus, so if anyone expresses an interest in keeping the license as is, you'd need to either convince them to change their mind or remove their contribution from future versions to apply the new license.

If you have an interest in doing this, sooner would probably be better. It's harder to track people down for consent if you can't reach them by the email in their git commit.

OpenSSL is in the [process of undergoing a license change](https://www.openssl.org/blog/blog/2017/03/22/license/). You might look there for some insight into what's involved.

**Comment by flovilmart** [comment]
@nbering thanks for the insights. Before it was transferred to the community, the code was under Facebook's CLA. After it's transfer, the CLA was removed and we probably fallback to th openSSL use case. Now that the code is transfered, I'm wondering where the BSD + Patents stands in terms of licence. @lacker any idea?

**Comment by flovilmart** [comment]
@joielechong I just checked again, and parse-server itself is released under BSD since day 0, so we're free of the issue!

**Comment by pewh** [comment]
I'm curious why there's a PATENT file ( https://github.com/parse-community/parse-server/blob/master/PATENTS) if it not released on BSD + Patents

**Comment by flovilmart** [comment]
it's original patents from Parse Inc. but the code was not released under BSD+Patents licence.

**Comment by joielechong** [comment]
@flovilmart: Glad it a BSD one! Agree with @pewh, could the PATENT file be removed?
