### ISSUE TITLE
Making adapters available to cloud-code

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#4121]
For now, I'm using `var AppCache = require('parse-server/lib/cache').AppCache` to access parse mail adapter through `AppCache.get(process.env.APP_ID).userController.adapter`, but I clearly feel it's unsafe to use.
Would it be possible to have an access to parse adapter through cloud-code?
Thanks

**Comment by buddy-ekb** [comment]
Since then the access to emailAdapter became more complicated and now it looks like `AppCache.default.cache[process.env.PARSE_SERVER_APPLICATION_ID].value.userController.adapter`

So I'm also wondering if there is a more robust way so as to not duplicate mail adapter credentials in cloud code.

**Comment by fcoufour** [comment]
I'm also looking for the best answer to this question :).

I currently use the same trick as you guys. Moreover, since Parse Server is configured loading a JSON configuration file in my case, I can't read the appId from the process env and I have to import the cache from the lib directory using an absolute path.
