### ISSUE TITLE
How to verify bank web gate response using cloud code

### ISSUE THREAD

**Issue by monajafi** [parse-community/parse-server#4216]
My scenario is:
1- Node.js code requests payment through some bank web gate with my callbackurl
2- user redirects to bank web gate
3- I should verify payment using callback url and node.js finally send push notification to android app
Is it possible to do this using cloud code ,how should it be done?

**Comment by montymxb** [comment]
Closing as this is not an issue with parse-server itself. What you're asking is more appropriately suited for stack overflow, and I would highly recommend you open an issue up there. 

Your case depends on the particular gateway you're accessing and it's API, both of these are outside the scope of parse-server. Again, since it seems this is something unrelated to an actual issue with parse-server this would be much more appropriate over in stack overflow.
