### ISSUE TITLE
Login with empty email (undefined) returns "Account already exists for this email address."

### ISSUE THREAD

**Issue by mat2cc** [parse-community/parse-server#4407]
We have deployed a [Parse Server on Azure](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Microsoft.ParseServer)

**Problem:** 
Adding User that is not assigned an email returns "Account already exists for this email address." error.

**How this occurred:**
This occurred when adding a new user to Parse.  We tried adding users through the parse dashboard, through an android application (given username and password) and though a Facebook login.  Each time no email is entered and is left as undefined.  We are given this error: "Account already exists for this email address." in the parse dashboard log and in the Azure server output.

When using back4app, adding users through the dashboard was no problem if the duplicate email was undefined.  I have also checked the server code for back4app and the parse-server code that was deployed on Azure.  There seem to be no differences that would cause this error.

**Comment by ciozmi** [comment]
I am experiencing the exact same issue with the same configuration. Let me know if you require any additional details and please advise on how to proceed to allow (or handle) user creation without providing an email address.

### Issue Description

Creating a new user (either through signing up or facebook login) **without** providing an email address (once has **already** been created without an email address) raises the "Account already exists for this email address." error. 

### Steps to reproduce

1. Create a new user  **without** providing an email address (either by signing up or logging in with Facebook)
2. Once successful, create another new user  **without** providing an email address (either by signing up or logging in with Facebook)
3. The error shown below is given.

#### Expected Results

A new user is created **without** providing an email address.

#### Actual Outcome

The new user is not created and an error is returned (see below).

#### Side Note
I have noticed after some experimentation that the error occurs in the following piece of code in src/RestWrite.js:
<pre>
      // If this was a failed user creation due to username or email already taken, we need to
      // check whether it was username or email and return the appropriate error.
      // Fallback to the original method
      // TODO: See if we can later do this without additional queries by using named indexes.
      return this.config.database.find(this.className, { username: this.data.username, objectId: { '$ne': this.objectId() } }, { limit: 1 }).then(results => {
        if (results.length > 0) {
          throw new Parse.Error(Parse.Error.USERNAME_TAKEN, 'Account already exists for this username.');
        }
        <b>return this.config.database.find(this.className, { email: this.data.email, objectId: { '$ne': this.objectId() } }, { limit: 1 });
      }).then(results => {
        if (results.length > 0) {
          throw new Parse.Error(Parse.Error.EMAIL_TAKEN, 'Account already exists for this email address.');
        }</b>
        throw new Parse.Error(Parse.Error.DUPLICATE_VALUE, 'A duplicate value for a field with unique values was provided');
      });
</pre>
Please advise on any fixes that can be applied in order to allow this new user creation without providing an email.

If not possible please advise on how to proceed and handle cases like this.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.8
  - Operating System:     Azure App Services
  - Hardware:             not sure
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Azure

- **Database**
  - MongoDB version: 3.4 (according to Microsoft)
  - Storage engine:  CosmosDB (not sure)
  - Hardware:        not sure
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Azure

### Logs/Trace

<pre>
Error generating response. ParseError {
  code: 203,
  message: 'Account already exists for this email address.' }
</pre>

**Comment by ciozmi** [comment]
Thanks for responding @addisonElliott. Have in mind that the parse server is hosted as an Azure App Service and not on Windows. I have tried the above and unfortunately have the same error.
But..

I have managed to resolve the issue! The fix was actually **very very very** simple! All I had to do was drop the User class and recreate it and voila! It now works!

After looking into the issue in depth, what happened was when Azure was deploying the parse-server and creating the database, it also automatically created indexes when creating the tables for the first time (and in the User class case, that included the username and email address). I have tried modifying the index to no avail, so just decided to drop and re-create the class and everything is now working as expected!

**Comment by mat2cc** [comment]
WOW!  Deleting and replacing the User table worked for me as well!

I was trying to change the initial User table from a mongoDB client ([Studio3T](https://studio3t.com/)) because I thought that might be the problem, with no luck.  It was probably because of the indexing as well. 

Thanks a lot!

**Comment by tai-x** [comment]
@ciozmi @mat2cc  I think I'm having the same issue, how did you "drop the User class and recreate it"? Do you have handy the mongo commands? This is happening on my production database so I'm kind of nervous.

Out of the blue, in my production installation (Parse 2.8.2 at Heroku + mongolab instance), I'm getting the account already exists when email is undefined. This is actually happening because Parse.FacebookUtils.logIn() is not being able to identify that there is another user with the same authData.facebook.id already in the database. Instead of logging in that user, it is creating a new one with a random username. Any clue @flovilmart? 

Note that this production environment's mongo db has not been touched for over 2 years. And I have a dev environment with the same exact Parse Server version and server code, and only happens in production.

**Comment by flovilmart** [comment]
@tai-x let's keep the discussion in your newly opened issue.
