### ISSUE TITLE
Unable to connect to Parse API (remotely in iOS only)

### ISSUE THREAD

**Issue by RCorsino** [parse-community/parse-server#4422]
React Native Error. (iOS is not working but perfectly works on Android)

Works on iOS if connected to a localhost parse but returns an error of Unable to connect to Parse API if connected to a remote parse.

ParseError {code: 100, message: "XMLHttpRequest failed: "Unable to connect to the Parse API""}

"parse": "^1.10.2",
"react": "^16.0.0",
"react-native": "^0.50.3",

**Comment by montymxb** [comment]
@RCorsino this really needs more info. It also looks identical to the post you made over in the [js sdk](https://github.com/parse-community/Parse-SDK-JS/issues/534). I'm closing this in favor of the other issue since this seems more related to a use issue with the JS SDK. 

If this issue is specifically for the server you an always reword and provide additional details and we can look into this (separately from the other issue on the JS sdk).

Also please don't post multiple copies of the same issue across multiple projects here. Generally you  should open an issue on one and we'll get back to you, unless you're having multiple issues.
