### ISSUE TITLE
Subscription.on(‘delete’, …) triggered when response is an error in cloud function beforeDelete. 

### ISSUE THREAD

**Issue by salesmendesandre** [parse-community/parse-server#4427]
### Issue Description

If the cloud function `Parse.Cloud.beforeDelete` is used to check if is valid remove an object from database and the response for that function is an error ( `response.error()` ), the funtion of subscription that receive the delete ( `suscription.on(‘delete’, … )` )  is triggered, but that is not supposed to happen. 

### Steps to reproduce
1.  Create a class
2.  Enable live queries for that class
3.  Create a subscrition.on('delete', ... ) for that class
4.  Create a cloud function beforeDelete for that class with this code
`Parse.Cloud.beforeDelete("NameClass", function(request, response) {`
          `response.error("Error on function beforeDelete");`
`});`
5. Delete one object from your code. Now you will be receive an error. The object is not removed from your table, but the function `subscrition.on('delete', ... ) ` is triggered.

### Environment Setup

- **Server**
  - parse-server version : 2.7.1
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Remote Other

**Comment by montymxb** [comment]
I didn't see anything in the docs clarifying whether this _should_ or _should not_ be the expected behavior. I'm assuming all other related cloud code functions use a similar approach to how `beforeDelete` would be handled. They may all continue regardless of an exception. For further checking I would think that `beforeSave` would be another example to compare against. If any other existing **before** cloud functions can cause execution to stop short this might be something we should look into.

**Comment by mainto** [comment]
I have same issue. Is there any update yet?

**Comment by mainto** [comment]
Still happen on parse-server version 3.0.0

**Comment by flovilmart** [comment]
@mainto do you want to provide a fix for it?

**Comment by mainto** [comment]
@flovilmart let me try. when it is ready, I will PR.

**Comment by mainto** [comment]
I make a PR #5031
