### ISSUE TITLE
allowClientClassCreation is not working

### ISSUE THREAD

**Issue by Nisthar** [parse-community/parse-server#4527]
I used https://github.com/parse-community/parse-server-example to host my parse server on heroku.

I have edited my `index.js` file:

```js
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  enableAnonymousUsers: process.env.ANON_USERS || false,
  allowClientClassCreation: process.env.CLIENT_CLASS_CREATION || false
});
```
I added `CLIENT_CLASS_CREATION` and set it to false.

My parse client is android. I am using this code:

```java
 Parse.enableLocalDatastore(this);
        Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
        Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId(getString(R.string.parse_app_id))
                .server(getString(R.string.parse_server_url))
                .build()
        );
 FacebookSdk.sdkInitialize(getApplicationContext());
        ParseFacebookUtils.initialize(this);

 ParseACL defaultACL = new ParseACL();
        defaultACL.setPublicReadAccess(true);
        defaultACL.setPublicWriteAccess(false);
        ParseACL.setDefaultACL(defaultACL, true);

        ParseObject object = new ParseObject("app3");
        object.put("user","TestUser");

        object.saveEventually(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                if (e == null) {
                    Log.i("Parse","SUCCESS");
                } else {
                    Log.i("Parse","FAILED");
                    e.printStackTrace();
                }
            }
        });
```

The query should fail. But its giving me `SUCESS`

What am i missing here?

**Comment by tolgaatam** [comment]
hey, 

i'm not sure if the booleanParser only parses strings directly coming from the environment variables, so my suggestion might not be working but you might want to try.

i assume the problem happens because you are passing the string 'false' to the main config and it is not being processed as the boolean false. rather than trying to set an environment variable yourself, use the envorinment variable:

PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION

this is a predefined environment variable and setting this to false should do the trick for you and you can clear your allowClientClassCreation from the config.
if this does not work, then parse server guys might be talking about some serious problems

you can find more default environment variables at src/Options/Definitions.js in parse-server code :)

**Comment by mryalamanchi** [comment]
@Nisthar the environment variables are set to type **String**. So you need to convert it from string to the **Boolean** type since both _enableAnonymousUsers_ and _allowClientClassCreation_ accept Boolean values only.

You can use "yn" package which does the job for you. So your code should look something like this :
```
const yn = require("yn");
.
.
.
enableAnonymousUsers: yn(process.env.ANON_USERS) || false,
allowClientClassCreation: yn(process.env.CLIENT_CLASS_CREATION) || false
```
This should solve the problem. 

After adding this, committing and pushing the code, Heroku's nodejs buildpack might give you errors saying "yn package was not found", then all you need to do is remove the node_modules from your local repository, do fresh ``` npm install``` and then set the Heroku config ```NODE_MODULES_CACHE``` to ```false``
``` heroku config:set NODE_MODULES_CACHE=false```

If still it gives you any other errors, then kindly continue to post the error here.
