### ISSUE TITLE
LiveQuery ClassNames

### ISSUE THREAD

**Issue by kaevee** [parse-community/parse-server#4544]
We have a project where the client creates arbitrary classes at runtime. We are restarting the services periodically(if need) to reconfigure the live query server. 

Is there a way where we can reconfigure the live query server at run time by adding and deleting classes?

**Comment by flovilmart** [comment]
At the moment it’s not possible due to the current architecture of the server and the live query server. However, what we could easily introduce is a pattern matching option to the list of liveQueryClasses, this way, you could perhaps use a common prefix in your class name and they would automatically match when they’re added by your clients.

**Comment by kaevee** [comment]
Adding pattern matching would be great. It will solve our problems. I have very little experience in Parse server development. I will explore the sources. If you have any suggestions, it would be very helpful.

**Comment by flovilmart** [comment]
Have a look for the option that defines the list of classes that are enabled for liveQuery through the codebase,

**Comment by kaevee** [comment]
We did not expect a solution that is clean and straightforward at one go. We will make changes. Thanks again.
