### ISSUE TITLE
Query for specific field in User class returning empty, even though data is there

### ISSUE THREAD

**Issue by davidyeiser** [parse-community/parse-server#4759]
### Issue Description

I think this is a permissions issue, and not a bug, but I'm not sure. I've [asked about it on Stack Overflow](https://stackoverflow.com/questions/50279683/parse-server-field-set-in-server-environment-inaccessible-on-front-end), but in case it's a but I'm reporting it here.

I'm using Parse Server to store data for my Node/React app and I am trying to setup a user invite system.

When a new user is created in addition to the default user/pass/etc. fields I create two additional fields that are arrays, one to hold invite codes and another to hold sent invites. This happens on the front-end (in `src`).

I can view the array of invite codes and the empty array for sentInvites in the Parse dashboard after the user is created.

When a user invites someone else I build an object that contains the invite code and the invitation email and store it in Parse in another field called `sendThisInviteNow`. This happens on the front-end as well.

Then on the server side, I use an `afterSave` trigger to send the actual email and then move the invite object from the `sendThisInviteNow` field to the `sentInvites` array.

After the new user has been invited I can see the updated results in the Parse backend. For example, in the `sentInvites` field, I see an array of the past invite objects:

````
[
  {
    "code": "SJmtxGzAz",
    "email": "david+test@pretendemailaddress",
    "status": "pending"
  },
  {
    "code": "rygQKlGfAG",
    "email": "david+tes2t@pretendemailaddress",
    "status": "pending"
  }
]
````

**The problem**: When I query the `sentInvites` on the front-end, even though I see the data in the Parse Dashboard, all that is returned is an empty array.

e.g.

````
componentWillMount() {
  const { user } = this.props
  const correctUserTest = user.get('username')
  const sentInvites = user.get('sentInvites')
  console.log(correctUserTest)
  console.log(sentInvites)
}
````

returns:

````
correctuser
[]
````

I'm thinking it's a permissions issue of some sort, but there's no indication of different permissions, it's very strange. It's almost as if the same field contains two separate items.

### Steps to reproduce

Below is my code that corresponds to the description above.

**When a new user is created**:

````
const inviteCodes = [
  shortid.generate(),
  shortid.generate(),
  shortid.generate(),
  shortid.generate()
]

user.set('inviteCodes', inviteCodes)
user.set('sentInvites', [])
````

**Front-end code for when an invite is sent**:

````
const user = Parse.User.current()
const inviteCodes = user.get('inviteCodes')

// Take the first
const inviteCode = inviteCodes[0]

// And then remove it
const newInviteCodes = inviteCodes.slice(1)

const inviteReady = {
  code: inviteCode,
  email: email,
  status: 'pending'
}

user.set('sendThisInviteNow', inviteReady)
user.set('inviteCodes', newInviteCodes)

user.save()
````

**afterSave trigger on the server side**:

````
Parse.Cloud.afterSave(Parse.User, request => {
  const user = request.object
  const sessionToken = !!request.user ? request.user.getSessionToken() : ''

  if (!user.existed()) {
    // Code for new user stuff goes here, welcome email, etc.
  }
  else {
    // Check to see if there's any invite to send
    const inviteReady = user.get('sendThisInviteNow')

    // If there's an invite ready to send
    if (!!inviteReady) {
      const inviteUrl = 'http://localhost:3000/sign-up?inviteCode=' + inviteReady.code
      const emailBody = renderEmailInviteBody(user, inviteUrl, inviteReady.code)

      sendMail(inviteReady.email, 'You have been invited!', emailBody)
        .then(() => {
          // Email was sent, now move invite from "to send" to "sent"

          // Setup new empty array and get any past invites
          const sentInvites = []
          const pastSentInvites = user.get('sentInvites')

          const pastSentInvitesArray = !!pastSentInvites ? pastSentInvites : []

          // Add past invites to array (if any)
          sentInvites.push(...pastSentInvitesArray)

          // Add latest invite
          sentInvites.push(inviteReady)

          // Save with updated array
          user.set('sentInvites', sentInvites)

          // And remove sent invite from "to send" field
          user.unset('sendThisInviteNow')

          // Update information
          user.save(null, { sessionToken: sessionToken })
        })
        .catch(error => console.log('send email error: ', error))
    }
  }
})
````

#### Expected Results

The array of objects would be returned when requested (as shown in the `componentWillMount()` example in the description above).

#### Actual Outcome

An empty array is returned.

### Environment Setup

- **Server**
  - parse-server version: `2.7.4`
  - Operating System: `macOS 10.12.4 (Sierra)`
  - Hardware: `iMac (Retina 5K, 27-inch, Late 2014)`
  - Localhost or remote server? `localhost`

- **Database**
  - MongoDB version: `mongodb-core: 3.0.4`
  - Storage engine:  Not sure?
  - Hardware: Not sure?
  - Localhost or remote server? `localhost`

### Logs/Trace

None

**Comment by davidyeiser** [comment]
It seems to be something other than that, because even when I refresh the page it still returns the empty array. Even though I see the data in Parse Dashboard.

**Comment by mullwaden** [comment]
Do you refresh the user object though? Because it won't do that for you automatically.

**Comment by JacobJT** [comment]
Are you making this front end check immediately after the save? Because you're going to get the results of yoru save at the end of beforeSave, not afterSave. So you get the resulting object about the same time afterSave is doing it's thing.  The sentInvites update doesn't happen until after some other asynchronous requests + server operations on another third party.  So, if you're trying to access this data immediately, you're not going to see it right away.

Does this request just generally not work? I.e. there's an object that you sent invites a while ago, and are now trying to view sent invites, but they're not appearing? Or is your issue just that it's not appearing immediately? If it's the latter, my suggestion would be to set up a cloud function that sends these invites, and only have that return after the invites have all sent, rather than using after save triggers to manage that.  Then, update the client when it gets a successful result from the sendInvites cloud function.

**Comment by davidyeiser** [comment]
@JacobJT It just generally doesn't work. Even long after the query has been executed (days, etc.) it still can't access the field created on the backend. There's a [comment](https://stackoverflow.com/questions/50279683/parse-server-field-set-in-server-environment-inaccessible-on-front-end#comment87744132_50279683) in the Stack Overflow question that I haven't tried yet. I'm going to see if that's the issue. I haven't explored cloud functions either, that may be the ticket out of this issue. I'll report back with findings on the SO comment.

**Comment by jeffreyjackson** [comment]
@davidyeiser is it the email field that youre having issues with?

**Comment by davidyeiser** [comment]
@jeffreyjackson No it's a newly created, custom Array field. Holds objects with user invite data (their unique code, email address and status).

**Comment by flovilmart** [comment]
@davidyeiser if your users are publicly accessible, that means any one querying the user table will be able to read the email address of the invitees

**Comment by georgesjamous** [comment]
My input on this is....

As I understand  the problem, 
- You are updating the user In an AfterSave hook
- Your data (newly created fields) is appearing on the cloud and you can see them in the dashboard
- Your data is not appearing in the front-end after you do user.save()

And I see you are using parse-server version: 2.7.4 so this problem should not happen since problems like this were fixed early in parse-server releases. (at least to my extent of knowledge and since I have been using parse since as far as I can remember )

Possible Causes:
- After save is called after the object is saved, and after you have received a successful response on the front end. (You will receive a successful response on the front end, even if AfterSave has not yet been completed) --> So make sure you do user.fetch() after you user.save() in the front end to get whatever new data has been added in AfterSave hook.

- You are doing user.fetch() after your user.save() but its so fast that the after save hook hasn't completed yet, try doing it after a delay to test the issue.

- You are caching the user. Try clearing the cache.


If none of these work:
- Try to use the latest Parse-Server build. See if the error persists
- Check the _SCHEMA class and make sure the new Key (field) exists
( Only do this if the field does not appear in the dashboard, if it does. Disregard this as it is of course added in _SCHEMA)

Hope this helps !
