### ISSUE TITLE
Is someone writing a parse SDK on Flutter Platform?

### ISSUE THREAD

**Issue by jzzhrqp** [parse-community/parse-server#4847]
I like Parse-server very much, but unfortunately now I can't find Parse's Skd on Flutter platform, so I very much hope that someone with awesomeness can write a parse-sdk-flutter, that would be great! Thanks to all the parse developers and the person who is about to write parse-sdk-flutter.

**Comment by oallouch** [comment]
"parse-server dart" on Google gave me
https://github.com/lotux/parse_server_dart

**Comment by dplewis** [comment]
@oallouch Thats kinda cool, never heard of Flutter or Dart before.

@flovilmart Have you looked at the package and how they added live queries.

**Comment by flovilmart** [comment]
Nope! Didn’t checked it!

**Comment by flovilmart** [comment]
Closing as answered :)!

**Comment by jzzhrqp** [comment]
https://github.com/lotux/parse_server_dart  ，This project is not perfect, can't work, and the author has not updated for a long time.

**Comment by flovilmart** [comment]
This is still a base to get started, opensource is hard and demanding, with your help, perhaps the SDK can be brought up to date :)

**Comment by mryalamanchi** [comment]
@flovilmart, Flutter offers the developers to communicate host (native code) and client side (Flutter) so the Android and iOS sdks can be used without fail. But again. having a Flutter sdk is anytime advantageous for the developers using it. Also, Flutter being a cross-platform tool will provide more agility and save time in the longer run. 
Will the community focus on developing a Flutter sdk for parse-server anytime soon?

**Comment by flovilmart** [comment]
@mryalamanchi I am not sure what you are asking. If you see value in a developing a flutter SDK, then you can start one and become a maintainer. You can always seek guidance across the different communication channels for particular implementation details.

**Comment by trongvn2010** [comment]
https://github.com/lotux/parse_server_dart This project isn't work for me. Anyone did this?

**Comment by flovilmart** [comment]
@trongvn2010 you should open an issue on this project then

**Comment by mryalamanchi** [comment]
@flovilmart yes I was suggesting to move towards hybrid client sdks rather than developing the individual client sdks. As many of the features are common across the mobile platforms so it helps the mobile developers and saves them a ton of time. Flutter is one such hybrid approach.
Having said that, I also acknowledge the fact that Flutter is very new in the market and will have to mature before the community can move towards developing the sdk. 
Yes, ofcourse, I am very much interested in doing that but will wait for the Flutter ecosystem to prosper and mature, since it just started gaining traction. 

Meanwhile, anyone worrying about not being able to use the parse-server client sdks in Flutter, don't be disappointed because Flutter supports using the [platform-channels](https://medium.com/flutter-io/flutter-platform-channels-ce7f540a104e) through which you can use native platform code.

**Comment by phillwiggins** [comment]
Try

https://pub.dartlang.org/packages/parse_server_sdk#-readme-tab-

**Comment by mryalamanchi** [comment]
@phillwiggins awesome work!
@flovilmart can you kindly look into this? This can be certainly taken into the Parse-server's official SDKs for Flutter.

**Comment by flovilmart** [comment]
> This can be certainly taken into the Parse-server's official SDKs for Flutter.

It’s been added to the website as part of the community projects.

**Comment by HerrNiklasRaab** [comment]
@flovilmart What needs to be done to move the "parse_server_sdk" repository to the "parse-community" organization? At the moment we don't feel really confident to go with "Flutter + Parse Server" because it is not really maintained under the hood of the main organization. Hope you understand what we are concerned about.

It has 170 stars on Github. Arduino, for example, is under the official SDKs and has 54 stars. It is also to expect, that Flutter will grow its popularity.

What are the showstopper for this? Missing license from contributor or manpower?

**Comment by davimacedo** [comment]
The Flutter SDK is an initiative and mainly maintained by @phillwiggins so it is actually his decision to move it or not to the parse-community organization. If he wants to do so, I'd be more than happy to move forward with this.

**Comment by TomWFox** [comment]
@davimacedo’s right, I would also be happy to see the SDK move into the community org.

**Comment by phillwiggins** [comment]
Hey

I've not had a chance in the past few months to do much with this either. I'd like to move it to the community, hopefully we can see it grow further!

**Comment by davimacedo** [comment]
Nice @phillwiggins ! Here it goes how the process works: https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/

I will add you as a member of the parse-community so you will be able to create a new repository. You should receive an invitation soon.

**Comment by phillwiggins** [comment]
All done @davimacedo.

I started by created a repository, but realised after it was probably best to just transfer ownership. The repository [Here](https://github.com/parse-community/Parse-SDK-Remove) needs removing and the one I have transferred needs the naming convention changing but it's free for the community to play with!

Once my current personal project is finished I will jump back on board and carry on improving this SDK.

Cheers!

**Comment by TomWFox** [comment]
Awesome, I've started a guide for the docs website ([draft PR](https://github.com/parse-community/docs/pull/671)).

@phillwiggins what do you think about moving your slack group over to the existing community one?

**Comment by phillwiggins** [comment]
Hey Tom

Yeah of course. I'm not sure how to do that but will figure it out!

**Comment by TomWFox** [comment]
@phillwiggins I didn't have anything fancy in mind, I just thought we'd setup whatever channels you'd like on the community slack and then you could post a link in your slack?

**Comment by phillwiggins** [comment]
@TomWFox 

Ah okay, can you invite mate to the Parse Slack group please. phill.wiggins@gmail.com

**Comment by TomWFox** [comment]
It says you're already in the group. Here is a public [invite link](https://join.slack.com/t/parseopensource/shared_invite/enQtNjk2NzY1NDU3NDkxLTgwOGM1ZjRhYTM5MTRiMmEwYWU5MTNiZWNiNzZjNzY0ODQwNzU1MGVlMWI2NTI2ZWQ3NTA1NDgyZWNiY2U2MjM) - it shouldn't expire so you could use this to share with people in your group.

**Comment by TomWFox** [comment]
I've added a flutter-sdk channel, let me know if you would like any others.
