### ISSUE TITLE
Distinct query - limit and order?

### ISSUE THREAD

**Issue by rihadavid** [parse-community/parse-server#4880]
Hi, I've just discovered a distinct query and I tried to use it to get unique comment authors from a list of comments. The query restrictions work well, but it seems that it is not possible to get like "5 newest authors", because the ordering and limiting do not work.

I think this is most probably not implemented, it would be awesome if somebody could do it :)
I have no idea how complicated this could be. What do you think @dplewis ? :) 🥇 
Of course, I can use just a usual query, but the distinct query seems much more efficient, I like it!

    var subcommentsQuery = new Parse.Query("Comment");

    //those work as expected
    subcommentsQuery.equalTo("pComment", savedObject);
    subcommentsQuery.notContainedIn("author", [editingUser, savedObject.get("author")]);
    if (savedObject.get("forAll"))
        subcommentsQuery.greaterThan("createdAt", addHours(new Date(), -36));

    //those does not work at all (when using the distinct query)
    subcommentsQuery.ascending("createdAt");
    subcommentsQuery.limit(1);

    return subcommentsQuery.distinct("author").then( ...

**Comment by dplewis** [comment]
@rihadavid As far as I can tell distinct for mongo doesn't support limit and sort options. It also returns a promise instead of a cursor. You can use the regular aggregate stages `group`.

http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#distinct

However the options it does support aren't implemented yet.
