### ISSUE TITLE
npm WARN deprecated uws@10.148.2: stop using this version

### ISSUE THREAD

**Issue by stage88** [parse-community/parse-server#4955]
### Issue Description

usw is deprecated: "npm WARN deprecated uws@10.148.2: stop using this version"

### Steps to reproduce

npm install
 
### Expected Results

Possibly remove uws as a dependancy since parse server fails back to ws anyway

### Actual Outcome

Got a warning when npm install

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2
  - Operating System:     MacOS
  - Hardware:             Macbook Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local

- **Database**
  - MongoDB version: 4.0.1
  - Storage engine:  default
  - Hardware:        Macbook Pro
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Local

**Comment by flovilmart** [comment]
Solved on master. 

You can work around the issue by pinning uws at the right version (10.148.1).


Also 2.8.2 is not the latest version anymore

**Comment by agwl-saurabh** [comment]
### Issue Description
npm WARN deprecated uws@10.148.1: New code is available at github.com/uNetworking/uWebSockets.js


and this issue 

make: Entering directory '/root/parse-server-example/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:10: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>


### Steps to reproduce
npm install

### Expected Results
Possibly remove uws as a dependancy since parse server fails back to ws anyway

### Actual Outcome
Got a warning when npm install

### Environment Setup
* **Server**
  
  * parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  * Operating System:     Ubuntu NodeJS 8.10.0 on 18.04 
  * Hardware:             2GB Memory/1vCPU/50GB hardDrive
  * Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean
* **Database**
  
  * MongoDB version: 4.0.2
  * Storage engine:  default
  * Hardware:        4GB Memory/2vCPU/50GB hardDrive
  * Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital Ocean

### Logs/Trace


I am not able to fix this issue I am using "parse-server-example" from git and i have seen the package.json and not able to understand what needs to change in dependencies for version update below is my package.json file i have updated the parse-server variable to latest

"dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "3.1.3"
