### ISSUE TITLE
Distinct only returns the object that it is checking no the remaining object

### ISSUE THREAD

**Issue by developerX** [parse-community/parse-server#4961]
I was curious to know if there is a way to retrieve the latest information only one level deep. 

I have a messages table, in the messages table I am using I have a fromUser, toUser, and a message. 

Both the user fields are pointers to actual users in the db.

I was hoping to get a list of all unique messages sent from the user or recieved by a user. 

I am trying this:
```
new Parse.Query(Messages)
    .equalTo('fromUser', new Parse.User({ objectId: userId }))
    .select(['message'])
    .distinct('toUser');
```

It does return a list of all unique users but it doesn't actually have anything else attached to the returned object just the user pointer. 

I was hoping for a return of the unique toUser with the remaining objects still being included. I've tried adding a select and an include but neither change the out come.

This is what is being returned:

```
{
  "result": [
    {
      "__type": "Pointer",
      "className": "_User",
      "objectId": "mbcfK621ST"
    },
    {
      "__type": "Pointer",
      "className": "_User",
      "objectId": "N4xZ97ExRU"
    }
  ]
}
```

What I was hoping to be returned would be, those results with the messages attached. Am I missing something or is there another route to accomplish this? 

Ultimate, goal is to to get a list of recent conversations with the latest message sent by or received by the user. 

Thanks for any advice

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.
