### ISSUE TITLE
Flutter SDK

### ISSUE THREAD

**Issue by ckarmy** [parse-community/parse-server#5271]
If you are interested in the Flutter parse server SDK you can collaborate in https://github.com/phillwiggins/FlutterParseSDK 😀

**Comment by addisonElliott** [comment]
Not familiar with Flutter but it's great that you're working on the SDK.

This issue will likely be closed because issues are meant for describing bugs in parse server only. 

With that in mind, the more appropriate way of *"advertising"* this SDK is to place it in the README or somewhere in the docs. I'm sure others may have different opinions, but my suggestion would be to place your link in the **Community Highlights** section of the docs here: [https://parseplatform.org/](https://parseplatform.org/)

**Comment by flovilmart** [comment]
Would be nice on the community highlights indeed! Feel free to open a PR there!

**Comment by ckarmy** [comment]
And in which repositorie I can edit this?

**Comment by flovilmart** [comment]
@ckarmy there you go! https://github.com/parse-community/parse-community.github.io
