### ISSUE TITLE
How to schedule a job in bitnami parse dashboard

### ISSUE THREAD

**Issue by ranjithr27** [parse-community/parse-server#5303]
Hi, 
i am new to parse, my requirement is to delete objects from a class older than 10 days in parse dashboard,
Can i please get the steps on how to setup this as a scheduled job in parse ?

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to the parse community forums](https://community.parseplarform.org)? We'll be happy to answer there. Post a link to your question here, so that we don't loose track of it! 

Thanks!
