### ISSUE TITLE
Dynamically changing parse server URL in iOS SDK

### ISSUE THREAD

**Issue by nebitrams** [parse-community/parse-server#5371]
Can iOS app switch between 2 parse-server dynamically without restarting the iOS App?

My usage scenario is as follows...

Currently my iOS App connects to parse-server on Heroku.  I am planning to split my users into two groups: premium and basic.  I have prepared two servers
1. Premium: https://abc1.server.com/parse"
1. Basic: https://abc2.server.com/parse"

I need to implement the logic to make to App connect to one of the two servers depending on the logon user profile. The app retrieves the logon user profile from the current parse-server and decide whether there is a need to switch to another server. 

I had implemented the following logic and it works.  However, it requires a force App restart because ParseClientConfiguration is initialised in the AppDelegate application:didFinishLaunchingWithOptions function.  Can the app re-point to another parse-server without restarting the App?

Sample code to determine server URL.

`if (User.Instance.IsPremium()) {`
`              let config = ParseClientConfiguration { (ParseMutableClientConfiguration) -> Void in`
`                ParseMutableClientConfiguration.applicationId = "abc"`
`                ParseMutableClientConfiguration.clientKey = "def"`
`                ParseMutableClientConfiguration.server = "https://abc1.server.com/parse"`
`              }`
`              Parse.initialize(with: config)`
`} else {`
`              let config = ParseClientConfiguration { (ParseMutableClientConfiguration) -> Void in`
`                ParseMutableClientConfiguration.applicationId = "abc"`
`                ParseMutableClientConfiguration.clientKey = "def"`
`                ParseMutableClientConfiguration.server = "https://abc2.server.com/parse"`
`              }`
`              Parse.initialize(with: config)`
`}`

In my primary view controller, I added a restart app logic.

`if (isServerURLChanged()) {`
`  DisplayMessage(title:"App Restarting", message:"App restarting to switch to Premium/Free tier.")`
`}`

**Comment by georgesjamous** [comment]
_Is been a long time since I dabbled with the front end code of this repo. And I am not sure i am still up to date with the internals._ That being said, in my opinion you have three options:

- Do not re-initialize the app, initialize once depending on the user's group, yet again...
How can you determine the user's group before connecting ? is it hardcoded? are they using the same database? What's the point of going duo servers?
 
- Do the logic in the backend, use a load balancer to split traffic depending on the path. I am not sure about Heroku, I'm speaking from an AWS perspective.

- Lastly, as far as I remember, parse-SDKs do not initiate any connection with the server upon initialization. And changing the URL does not affect the SDK. I guess it's safe to provide an internal function to change the URL internally. **I suggest you open a ticket in the iOS, Android or JS repo of the project** since its an sdk feature/issue/request.

**Comment by nebitrams** [comment]
Thanks for giving some insight into this.  Some details

1. I determine the user group by running a Parse cloud function.
1. Both servers point to the same database.
1. I plan to use 2 different heroku servers:
a. Paid heroku server for Premium users.
b. Free heroku server for Basic users.

The logic of switching between server A and B works well but the downside is that I need to force the user to restart the App.  It would be nice if I can do so without having to restart the App.

I don't have access to load balancer and also the server routing need to depends on user profile from database.  Therefore load balancer might not work.

You are right on the last point.  This topic should belong to the client SDK.
