### ISSUE TITLE
How to use an existing mongodb with parse

### ISSUE THREAD

**Issue by dopyoman** [parse-community/parse-server#5429]
Hey is there a way to use Parse with an existing mongodb? Lets say we have a python project that used mongo for the db. Can we put parse in front of the db to create a server web clients can use?

**Comment by georgesjamous** [comment]
@dopyoman your question is best suited on StackOverflow, check this current thread https://github.com/parse-community/parse-server/issues/5419

---

Nevertheless, I will try to answer your question since you seem new to parse-community.
First of all, please read the documentation/wiki and run a local development test project, save and query some objects to get an idea of what parse is and how data is saved in the database.

Now, to answer your question, yes, but you need to migrate your current data.
Parse saves data to MongoDB in the form of an object, each object has an `objectId` and some other default fields. Without migration, an object will not be read correctly from mongo and you risk having corrupted data all over and errors firing in your parse-server.

What you have to do is.
Learn more about parse (it easy!), start a local server to see how it works and how data is saved, then draft a migration plan of your current data and run the migration script. 
Then, you can use parse-server correctly.


Please close this ticket as it is not an issue, and it is very unlikely that you will find another answer looking at issues.

**Comment by acinader** [comment]
@dopyoman gonna close this out.  Feel free to re-open if you think we're missing something and this is an issue with parse-server.

**Comment by dopyoman** [comment]
@georgesjamous Thank you for taking the time to respond. Basically what you are saying is we would have to take each document and migrate it through the parse api for it to work correctly. Again thank you for taking the time to answer.

**Comment by georgesjamous** [comment]
If you want to access your documents from the Parse-API, yes you have to migrate your data through the Parse-API. That way parse-server correctly creates the schema for each class/collection.

Also, if you have relationships between your existing documents, you have to fix/replace the Ids by the ones created by parse, since parse generates a new id for each object. You can also take advantage of Pointers and Relations available with parse. Everything well documented in the docs.
