### ISSUE TITLE
Environment Variables are not used at all for Express based Parse Server environments

### ISSUE THREAD

**Issue by asdf01** [parse-community/parse-server#5731]
Hey Guys

I've been running parse server through express for some time now.  Looking at the the [readme file](https://github.com/parse-community/parse-server/blob/master/README.md#using-environment-variables-to-configure-parse-server) it looks like some features can be defined through environment variables.  

Specifically, I tried to start up my parse server environment with a readOnlyMasterKey.  Looking at [Options/Definitions.js](https://github.com/parse-community/parse-server/blob/master/src/Options/Definitions.js#L301), the file seems to suggest that I can achieve this by specifying the PARSE_SERVER_READ_ONLY_MASTER_KEY environment variable.  This didn't work.  

The only way I could get it to work was to pass in a readOnlyMasterKey option into the ParseServer constructor, something like:
```
var api = new ParseServer({
  ...
  appId: process.env.APP_ID,
  masterKey: process.env.MASTER_KEY,
  readOnlyMasterKey: process.env.PARSE_SERVER_READ_ONLY_MASTER_KEY,
  ...
});
```

Looking at the source code, it looks like "env" field in Options/Definitions.js is only really used by the [cli parse server startup method](https://github.com/parse-community/parse-server/search?q=%22Options%2FDefinitions%22&unscoped_q=%22Options%2FDefinitions%22)

The only other usage of Options/Definitions.js is in [defaults.js](https://github.com/parse-community/parse-server/blob/d83a0b680854f52ce30205d3558c0133d7f8cf19/src/defaults.js) and that just gets the default values.

So, is the readme slightly inaccurate?  As in, the environmental variables method of configuring parse server is reserved for cli based startups.

Or is the code slightly wrong?  As in, for express based startups, the code is meant to use Definition.js defaults -> environment variables -> ParseServer constructor options

Or is my usage of parse server wrong?  As in, this feature is working for everyone else using express based parse server.  

Thanks.

**Comment by davimacedo** [comment]
I understand that the env vars are (and should be) only used when starting through CLI since you can set your own env vars when "manually" instantiating Parse Server (pretty much like you did).

**Comment by asdf01** [comment]
Hi @davimacedo.  Thanks for looking into this issue.  

> I understand that the env vars are (and should be) only used when starting through CLI

I'm guessing you reached this understanding simply because that's how the app behaves and not through any fundamental core belief on how things should work.  

> you can set your own env vars when "manually" instantiating Parse Server

That method involves changing the source code.  It would obviously be a lot more flexible if I can alter the behaviour of the app by simply changing the build process to include a new environment variable.  And that is what the readme suggests should be possible.  

I'm not too interested in solving the immediate problem of getting the readOnlyMasterKey to work.  I'm interested in whether parse server is implemented incorrectly in this minor aspect or whether the documentation is incorrect.  

Obviously many hours were lost in figuring this problem out.  If either the app was changed to be consistent with the doc or the doc was changed to be consistent with the app we could save a lot of people around the world many hours of frustration which they can possibly spend with their children.  

So I'm trying to figure out what the community believes is the correct behaviour and correct approach to address this issue.  Thanks

**Comment by davimacedo** [comment]
In my personal opinion, I think that Parse Server current behavior regarding env vars is consistent and I agree with you that the README file could be more clear about it. Maybe we could change to something like this: "When using the CLI, you may configure the Parse Server using environment variables:"

**Comment by asdf01** [comment]
Hi @davimacedo .  Thanks for your continued interest.    

> I think that Parse Server current behavior regarding env vars is consistent

I wouldn't really agree that the behaviour consistent.  Because of a subtly different deployment mechanism, environmental variable based configuration don't work at all.  That just sounds weird.  But I do agree that changing the behaviour in the code now would have a degree of risk associated with it.  

If people are not expecting the changing, some value they set as a environment variable during the test phases of their project all of a sudden starts taking effect several iterations into the production phase of this project.  That would not be good.  

This might be a good change to make in a major version, as a breaking change.  But it looks like we already missed the boat with 3.x.  

For anyone that's interested, we are looking into making a simple change to our fork of the project to make this work.
[defaults.js](https://github.com/parse-community/parse-server/blob/master/src/defaults.js#L22)
i.e. 
change:
```
const DefinitionDefaults = Object.keys(ParseServerOptions).reduce(
  (memo, key) => {
    const def = ParseServerOptions[key];
    if (def.hasOwnProperty('default')) {
      memo[key] = def.default;
    }
    return memo;
  },
  {}
);
```
to: 
const DefinitionDefaults = Object.keys(ParseServerOptions).reduce(
  (memo, key) => {
    const def = ParseServerOptions[key];
    if (def.hasOwnProperty('default')) {
      memo[key] = def.default;
    }
    var envVar = def.env;
    if(envVar) {
      var envValue = process.env[envVar];
      if(envValue) {
        memo[key] = envValue;
      }
    }
    return memo;
  },
  {}
);
```
This would allow us to add features into our parse server environments in the future like PARSE_SERVER_READ_ONLY_MASTER_KEY without having to change the code.  

Thanks @davimacedo for your support and contributions to the parse server project.  Without people like you, freeloaders like us won't have jobs.  Peace.

**Comment by davimacedo** [comment]
You can always expect peace from my side. I just have a different opinion for this case :). Maybe @acinader and @dplewis could also share their thoughts.

Let me explain why I disagree with you. It is not a matter of a breaking change nor how hard it would be to be changed, but it is really weird for me the behavior of a lib changing with env vars. There are two different ways to use Parse Server:
- Running it as program through the CLI: for this case, it makes totally sense to have env vars changing the program behavior instead of sending each of the params as arguments;
- Installing the parse-server package, instantiating the Parse Server class and using it in your own program that you are writing: for this case, in my personal opinion, I think that it does not make any sense to have env vars changing the behavior of a lib that I'm using. It would be an unexpected behavior of a lib. In a lib, when instantiating an object, the program that is using the lib is the one responsible to send all the configuration options in the constructor and create its own env vars if needed. It probably makes sense for you because you are thinking only in the simple case in which you have an Express.js app mounting a single instance of Parse Server. But let's imagine other scenarios and enumerate some reasons for not allowing env vars to change the Parse Server object behavior:
1. If you have multiple instances of Parse Server mounted in different endpoints, how env vars would work?
2. If I have a more complex application in which I am mounting other middlewares and not only Parse Server. Now imagine that I decide to create an env var called "cloud" (or something) to be used in other part of the application. Will it break the lib I am using? Now imagine how much time a developer will spend to figure out that the problem is related to an env var that changes the behavior of a lib that the program is using.
3. I don't know any lib in which an env var can change its behavior. Do you know some? The ones I've used allow me to setup the object by sending the options when instantiating the object. It is up to me to create my own env vars and send them when instantiating the object.
4. Why Express.js requires me to do `app.listen(port)` instead of only `app.listen()` and a convenient env var called PORT?
5. It is totally out of the responsibility of Parse Server object to access `process.env` and play with the vars. The program that is using Parse is the one responsible for this. The program should create the env vars that it needs and pass to Parse Server object in the initialization, like you can see in parse-server-example: https://github.com/parse-community/parse-server-example/blob/master/index.js#L14
6. I don't know if you are running Parse Server using the parse-server-example project, but I see that the allowed env vars there are not exhaustive and, in the case you are using it, I think you should open an issue in that repository to include all Parse Server env vars there.

Again, I am not here to fight. I just want to help with my thoughts. If the community have a different opinion, I have no problem to move forward with your suggestion.

**Comment by santiagosemhan** [comment]
I totally agree with you @davimacedo. I think point 5 its the most important one. Don't rely on ENV vars without explicitly set options in express based installation.
