### ISSUE TITLE
Parse Error doesn't contain message property but error  property instead

### ISSUE THREAD

**Issue by Tybi** [parse-community/parse-server#5749]
Hi, I try to implement [reset password with ajax mechanism](https://github.com/parse-community/parse-server/pull/5332/files/a8d95042e6012fe68782b409b34158777eb20f5a) in my application. It works good but if the token is invalid or the password doesn't match the policy. I receive an error formatted like this : 
`{"code":-1,"error":"Failed to reset password: username / email / token is invalid"}`  

### Expected Results
Shouldn't the error have this format instead 
`{"code":-1,"message":"Failed to reset password: username / email / token is invalid"}` like all Parse.Error ? 
### Environment Setup

Localhost

### Logs/Trace

`error: Parse error: Failed to reset password: username / email / token is invalid {"code":-1,"stack":"Error: Failed to reset password: username / email / token is invalid\n    at config.userController.updatePassword.then.then.result (/Users/tiby/Dev/DWA/wip/dwastudio-api/server/node_modules/parse-server/src/Routers/PublicAPIRouter.js:212:12)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"}`

**Comment by davimacedo** [comment]
@Tybi thanks for reporting. Would you be willed to write a failing test?

**Comment by Tybi** [comment]
@davimacedo Just to be sure, you want I write a failing test case in PublicAPI.spec.js ? If it the case I can do it  tomorrow.

**Comment by davimacedo** [comment]
I think https://github.com/parse-community/parse-server/blob/master/spec/PasswordPolicy.spec.js would be a better place. Thanks for your help!

**Comment by Tybi** [comment]
Ok but the problem does not only appear when the password does not comply with the policy ! It appears also when missing username or if the token is no longer valid !

**Comment by davimacedo** [comment]
Got it. So PublicAPI.spec.js actually seems the best file.

**Comment by Tybi** [comment]
I made the modifications on the tests cases wich I think should return message field instead of error [here](https://github.com/Tybi/parse-server/commit/bf97812eed205318c22eae6c53a14d05722b5639). Is it that you wanted ?

**Comment by davimacedo** [comment]
@Tybi thanks for your help. I've just checked your failing tests. You think that the error response should be in the format { code, message } instead of the current { code, error }, right? When I looked at the issue for the first time, I agreed with you. But I've just investigated further and found out that the REST API should actually respond errors in the { code, error } format as you can see [here](https://docs.parseplatform.org/rest/guide/#response-format) and [here](https://github.com/parse-community/parse-server/blob/master/src/middlewares.js#L310).

I agree with you that it's a little bit confusing because Parse.Error object has properties code and message while the REST API actually returns { code, error }. On the other hand, I think that this change would be really hard since it would probably break most of the current SDKs. In my opinion I think that the benefits it would bring are not worth for the effort and risks.

Please let me know if you agree with my opinion.

**Comment by Tybi** [comment]
OK I have never user the api and didn't know that the error object was different between the api and others. I found this because in my client app I have a method that handle error based on the fact that error object should contain code and message properties.I wanted to know if it was normal or no. So I understand now and I'am agree with you. 
I close the issue. 

Thanks for your explications.
