### ISSUE TITLE
backend processing time is too long for some file upload request with AWS S3

### ISSUE THREAD

**Issue by hoffergg** [parse-community/parse-server#5766]
Hi,
I got those logs from AWS load balances which showed some very slow or time-out file upload requests to S3.
![image](https://user-images.githubusercontent.com/9494996/60703903-87af3380-9f35-11e9-9235-6ce1e79d28bb.png)

**Comment by davimacedo** [comment]
This issue is most likely to be related to your environment setup than to the Parse Server itself. Could you please re-open the issue following the [template](https://github.com/parse-community/parse-server/issues/new?template=---report-an-issue.md) and adding as more details as you can about your environment? Thanks.
