### ISSUE TITLE
Parse Android SDK Error : 209 : Invalid session token When un-Installing then Re-Installing the app

### ISSUE THREAD

**Issue by outshot** [parse-community/parse-server#5949]
Every time i uninstalled my app (User is not logged Out) Then i re-install the app i am getting 
209: Invalid session token to all my requests to Parse Server.
I am using Parse 1.19.0 and Parse Server version 3.6.0

After Un-Installing and re-installing the app and re-opening it i am supposed to be redirected to the SignIn screen of my App but i am redirected to the Home Screen as if i am logged in and all requests made by the home screen return Error 209

**Comment by davimacedo** [comment]
This problem seems to be really specific to your app and the code that you wrote. I am not sure we will be able to help you here. I'd suggest you to open a question in stack overflow including as more details as possible and the pieces of code that you are using to check if the users is logged in or not.
