### ISSUE TITLE
Error Occurring Using Parse.Cloud.beforeLogin

### ISSUE THREAD

**Issue by KAIOAVILA** [parse-community/parse-server#5998]
### Issue Description

I'm implementing a check to make sure the user can sign in to the app, but an error occurs while trying to log in to the app.

For the error to occur, the class User must have a column with file and the record must have some file, if null works normally

### Steps to reproduce

Cloud implementation code snippet
```ts
Parse.Cloud.beforeLogin(async request => {
    const { object: user }  = request;
    if(user.get('deletedAt')) {
        throw 'Access denied, you have been banned.';
    }
    
});
```

`3|AP | Error: Tried to encode an unsaved file.
3|AP |     at encode (/home/user/api/parse-api/node_modules/parse/lib/node/encode.js:73:13)
3|AP |     at _default (/home/user/api/parse-api/node_modules/parse/lib/node/encode.js:126:10)
3| AP |     at ParseUser.toJSON (/home/user/api/parse-api/node_modules/parse/lib/node/ParseObject.js:578:42)
3| AP |     at object (/home/user/api/parse-api/node_modules/parse-server/src/triggers.js:540:23)
3| AP |     at success (/home/user/api/parse-api/node_modules/parse-server/src/triggers.js:273:14)
3|AP |     at <anonymous>
`

I was checking and an error is occurring on the user who has a file and when doing the code he can't pass this point

![Captura de Tela 2019-08-29 às 15 28 12](https://user-images.githubusercontent.com/2415473/63966447-b1866180-ca71-11e9-91f9-2fd09390d7c4.png)

**Comment by davimacedo** [comment]
Thanks for reporting. This PR should solve this issue: https://github.com/parse-community/parse-server/pull/6001/files

**Comment by kvnkuang** [comment]
Just want to report another issue surrounding this.

When logging in with an Auth provider, the same error occurs if that user has one or more files associated.

I spent some time investigating this problem and found that this error was triggered by this block of code: 
https://github.com/parse-community/parse-server/blob/44015c3e351fc7cf0ac3e99bc64738d35ddc3cba/src/triggers.js#L749-L764

Specifically, when encoding a file object with `toJSON()`, because the object was not expanded, it has no `url` property and hence cause [this block of code](https://github.com/parse-community/Parse-SDK-JS/blob/842c42cb7ab52f163f2566b8485004c3f0a78f35/src/encode.js#L46-L50) to throw an error:
```
  if (value instanceof ParseFile) {
    if (!value.url()) {
      throw new Error('Tried to encode an unsaved file.');
    }
    return value.toJSON();
  }
```

Similar to the fix introduced previously (#6001), all we need is to expand file objects before passing them to the trigger `runBeforeLoginTrigger` in [`RestWrite.js`](https://github.com/parse-community/parse-server/blob/master/src/RestWrite.js):
```
  // Cloud code gets a bit of extra data for its objects
  const extraData = { className: this.className };

  // PROPOSED FIX: expand file objects
  this.config.filesController.expandFilesInObject(this.config, userData)
  
  const user = triggers.inflate(extraData, userData);

  // no need to return a response
  await triggers.maybeRunTrigger(
    triggers.Types.beforeLogin,
    this.auth,
    user,
    null,
    this.config,
    this.context
  );
```

I am happy to prepare a pull request with the proposed fix.

**Comment by dplewis** [comment]
@kvnkuang Can you open a new issue? We don't want it to get lost.

**Comment by kvnkuang** [comment]
Thanks! Issue created #6871.
