### ISSUE TITLE
Documentation concern

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#6047]
I am really concerned about the pace at which changes and releases are being pushed arbitrarily with no documentation. Ever since we upgraded to 3.0 one needs to be fully following the repo to catch-up as some of these changes have gone under the Radar with no consideration or updating of the docs. I hope I am wrong about this and that this wonderful project does not become a project for a select few. Its important to note that this project has since stopped growing and I am beginning to wonder if its not worth it to just migrate back to firebase.

**Comment by TomWFox** [comment]
As a follow up to @mtrezza’s point about encouraging the documentation of new features. I think it would be a good idea to use [pull request templates](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) to highlight key points of the contributing doc such as providing documentation.

**Comment by omairvaiyani** [comment]
Here, there are clearly some very good concerns and equally good suggestions to mitigate them. I'll add one such suggestion, and hopefully we can get a plan underway to make sure everyone's happy, on the same page and can see the roadmap ahead.

There are a few too many locations that store information for users looking to learn, or finding solutions. Instead of having the github README, and github Wikis and parseplatform.org guides - we should just remove the wikis, have a short README that just points users to the guides and work towards a cross-language guide:
- I don't think GraphQL will replace SDKs in their entirety anytime soon
- Parse-Server guides should be merged with Cloud-Code

A community questionnaire to determine usage behaviour and statistics will greatly inform the future roadmap.

**Comment by TomWFox** [comment]
I totally agree on removing wikis and README content, happy to take that on.

**Comment by mtrezza** [comment]
Another minor thing, it would be nice to see release notes consistent across repos.

For example, the new release of [Parse iOS SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases) has all changes in the change log, but none mentioned in the release log which can be confusing.

**Comment by TomWFox** [comment]
@mtrezza Ha, as you've noticed, I fixed that specific example, but yes changelogs should be a lot more consistent, @omairvaiyani suggested some packages/conventions we could use [here](https://github.com/parse-community/parse-server/pull/6045).

**Comment by davimacedo** [comment]
I love the ideas here and I think that we can really have a much better documentation experience by moving forward with them!

I've just created a project so we can track the progress of the ideas we generated here and some other threads: https://github.com/parse-community/parse-server/projects/8?add_cards_query=is%3Aopen

Feel free to change/suggest changes to the tasks and grab any of them for execution.
