### ISSUE TITLE
Memory leak issues when upgrading form parse server ‘~2.x’ to ‘~3.x’

### ISSUE THREAD

**Issue by n-so** [parse-community/parse-server#6061]
### Issue Description
Hi,
When upgrading from parse-server ‘~2.x’ to ‘~3.x’
I started getting memory leaks issues.
I searched the web and tried many ways to fix this, the only solution that worked was to set enableSingleSchemaCache: true,
But I do not what to use this solution for production .(I don't want to take any risks)
Is there any other solution for this?

attached is a screenshot : comparison of two heap dumps taken 2 minutes apart
![image](https://user-images.githubusercontent.com/55482152/65130269-c49fa800-da05-11e9-9203-f964c2962812.png)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :'~3.x'
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server?  AWS

- **Database**
  - MongoDB version: 4.0.3
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? AWS
### Logs/Trace
No errors or strange messages reported, everything working as usual, just memory increasing.

**Comment by dplewis** [comment]
@n-so You can check out [this](https://github.com/parse-community/parse-server/issues/4247) for possible solutions when not using enableSingleSchemaCache. I don't believe those solutions have been implemented since a solution already exists. Feel free to try and test them for yourself. We will try to look into it also.

@acinader @davimacedo Should enableSingleSchemaCache be set to true by default? I think it pretty harmless.

**Comment by davimacedo** [comment]
Yes. I think it should be set by default. We'd need to mention it in the next release and ideally also the downsides of it.

**Comment by n-so** [comment]
Hi @davimacedo ,
Are there any risks  when setting enableSingleSchemaCache to true?
What are the downsides of enableSingleSchemaCache?

**Comment by dplewis** [comment]
The current implementation creates a new cache per request. This is to prevent side effects between requests. Using enableSingleSchemaCache is basically the same as disabling cache.clear().


Does cache.clear() gets called after every request? If not, implementing that would fix your memory issue while minimizing side effects

**Comment by dplewis** [comment]
@davimacedo does cache.clear() gets called. I couldn’t find it. Where should we put it.

**Comment by davimacedo** [comment]
@dplewis @n-so Just to make sure that we are all in the same page. This is what happens at each request:
 - This middleware (which run each request) retrieves the Config object [here](https://github.com/parse-community/parse-server/blob/master/src/middlewares.js#L121)
- In order to return the Config object, actually, at each request, a new Config instance is created and a new instance of SchemaCache as well [here](https://github.com/parse-community/parse-server/blob/master/src/Config.js#L30)
- [Here](https://github.com/parse-community/parse-server/blob/d3810c2ebac300b8ed9a04f360d63e77f40f91aa/src/Controllers/SchemaCache.js#L21) you can find the difference between enableSingleSchemaCache=true and enableSingleSchemaCache = false

If enableSingleSchemaCache is enabled, a single key is used and therefore the same cache is re-used in all requests. On the other hand, if enableSingleSchemaCache is disabled, a new key is generated at each request. The memory leak happens because the cache that was stored in each request is never cleaned. So, at each request, more cache is accumulated unnecessarily, and the memory continue growing.

I was first thinking about adding a middleware [here](https://github.com/parse-community/parse-server/blob/master/src/ParseServer.js#L175) to clean the cache at the end of each request. But I am afraid of jobs, push notifications (others?) routines that could have to continue running even after returning the response to the client.

Another option would be a TTL (maybe an additional parameter to Parse Server) associated to each of these keys. Then we could have a process cleaning these caches.

@acinader @dplewis thoughts?

**Comment by kcolton** [comment]
> I was first thinking about adding a middleware here to clean the cache at the end of each request. But I am afraid of jobs, push notifications (others?) routines that could have to continue running even after returning the response to the client.
Worst case If something referenced the cache after it was cleared at end of requests, wouldn't it just refetch the schema from the DB? same as if the cache happened to expire. 

> Another option would be a TTL (maybe an additional parameter to Parse Server) associated to each of these keys. Then we could have a process cleaning these caches.
This is different than `schemaCacheTLL`?

Seems like that would already handle freeing the space associated with the schema cache keys themself. Are you referring to "keys" on the Config object generated per request? Not sure I follow there.

Guess I'm not following how schema values in the various schema caches would be source of memory leak when there is a `schemaCacheTTL` at work. Is it from the nature of how `lru-cache` is implemented?

**Comment by dplewis** [comment]
@kcolton I agree, I don’t think clearing the cache after each request would have side effects. 

The SchemaCache is used to checking if classes and fields exist in the database without hitting the DB. Pushes and Jobs have already made writes and queries. After the request is over I don’t see how they would still use the cache.

I can do a PR and see how this would run against tests.

**Comment by davimacedo** [comment]
If you take a look [here](https://github.com/parse-community/parse-server/blob/master/src/Routers/FunctionsRouter.js#L71), you will see that the job is started and lef executing while the response is returned right away. It means that the request will end (and the cache will be cleaned) before the job finishes to execute. The push notification has a similar process. Probably other features as well. I believe that cleaning the session will not generate bugs as the schema will probably be cached again in the next time that the job needs it. But processes like jobs and push notifications will continue being cause of memory leak. That's why I think that a TTL solution would be the best one. But cleaning the cache in the end of each request will probably solve 99% of the problem. And since it seems really easy to be implemented, we should probably go for it. Will you tackle this one, @dplewis ?
