### ISSUE TITLE
Best way to delete a user (when requested)

### ISSUE THREAD

**Issue by SebC99** [parse-community/parse-server#6137]
We have an option in our app to delete a user account, but the current Parse SDK and Parse-server methods doesn't allow to do so:
We need to: 
- delete the user (and all its data)
- logout the user (to remove all local currentUser file & pointer)

By deleting the user causes the sessionToken to be invalid and the SDK logout methods fail.
If we start by the logout, there's no way to ensure safe removal of the current user (not allowing for other users to delete a user data)

Any idea on the best way to do it with Parse current user management system?
Thanks

**Comment by danielmartinprieto** [comment]
We use a cloud function for this. Also, you can safely ignore the logout error in the client because even if it fails, it deletes the auth token client side, so the user will be logged out anyway in the client after you’ve run the SDK function.

**Comment by mtrezza** [comment]
Create a cloud code function for this and you can log out the user on the client immediately.
In cloud code you can delete all user related objects with the `{useMasterKey: true}` option.

If deleting all user data is resource expensive, you may want to just invalidate the user (e.g. remove username, password, authData) and schedule the deletion of all other objects during a time when resources are cheap.

**Comment by SebC99** [comment]
We already have a cloud function for this, but we don’t want to simply use the masterkey to avoid having a function able to delete a different user than the current one.
@danielmartinprieto we do that, but with iOS SDK, when the logout fails, the callback is never called (not even with an error) so we are then stuck...

**Comment by mtrezza** [comment]
@SebC99 you are looking for best practice. It is not best practice to manage the user deletion client side. It depends on your use case, but the arguments you gave so far do not corroborate that.

Why it is not best practice:

- You cannot change the deletion logic once it’s out there.
- If you change classes or logic server side, the client side deletion function may fail and the user cannot delete their accounts. The error codes are may only be client side, so you may not even notice it for a long time.
- You duplicate code because in most jurisdictions a user can request e.g. by email to have their account deleted. So you’d have to do it for them.
- If the client side account deletion fails for whatever reason and you don’t notice that, you are keeping records of the user without their consent. That’s against privacy laws in most jurisdictions and can cause hefty fines. IANAL, but if the court rules that you did not use best practice because you implemented such code client side it can be considered negligence.
- Logging client deletion is easier when it’s done server side. If you are serving users of EU nationality or users of any nationality within the EU you have to comply with GDPR, in which the erasure of user data has to go into an audit log.

If you want to avoid that the function deletes a different user, because of

a) vulnerability
The user who calls the cloud code is `request.user`. Only delete the calling user. If you send the user ID as a parameter to the cloud code, that would be unsafe without further checks.

b) code errors
Add test cases that ensure that user deletion does not work for a different users, before you deploy new code.

**Comment by danielmartinprieto** [comment]
@SebC99 indeed, it seems more like a client SDK issue, because we're using the JavaScript SDK and it does throw the error (which we swallow because we know from the code that it does remove the logged in user client-side.)

**Comment by GoGross** [comment]
You need to create relevant ACL for each user data such that only a user can write and access their own data. When it comes a time to delete, a user delete request would simply iterate over all the subClasses to delete their data.

**Comment by GoGross** [comment]
You need to create relevant ACL for each user data such that only a user can write and access their own data. When it comes a time to delete, a user delete request would simply iterate over all the subClasses to delete their data. Proper ACL using roleNames which can be public incase someone with admin rights or access has to effect the delete operation.

**Comment by mtrezza** [comment]
@SebC99 Does this work for you?

```
func deleteAccountButtonClicked() {

    PFCloud.callFunction(inBackground: "deleteAccount", withParameters: nil) { _ in
          // delete user and session in cloud code

        PFUser.logOutInBackground() { (error) in
            // error will be code 209 "Invalid session token"
            
            deleteLocallyStoredUserDataInMemoryAndFileStorage()
            showLoginView()
        }
    }
}
```

`PFUser.logOutInBackground` will return with error, which is expected, but the SDK deletes the locally stored current user data nonetheless.

**Comment by SebC99** [comment]
We do exactly that but the logOutInBackground does not call the callback...

**Comment by mtrezza** [comment]
@SebC99 Can we close this question about best practice and continue to investigate the callback issue in https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1462#issuecomment-544687117 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SebC99** [comment]
Yes !
