### ISSUE TITLE
Severe MongoDB performance drop with anonymous users on large _Users collection

### ISSUE THREAD

**Issue by BufferUnderflower** [parse-community/parse-server#6219]
### Issue Description

Some queries become very slow because of frequent `COLSCAN`  taking up to ~1.5 sec on a collection with 2.000.000 `_User`s. 

### Steps to reproduce

1. Enable anonymous login feature. (not sure this makes any difference)
2. Populate a collection of 1-2 million users with _Session for each
3. Observe high (MongoDB) cpu usage (5-6 cores 100% load) and slow queries involving session tokens, functions impersonating users, login.

### Expected Results
 
Ideally there should be no performance issues when collections managed by Parse grow in size.

### Actual Outcome

High CPU usage (5+ cores), 1+ second latency, parse-server sometimes crashes with error "connection pool closed"

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0 (db was initially populated on 2.8 iirc)
  - Operating System:    linux
  - Hardware:  6 cores 16 GB  VPS
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): DigitalOcean

- **Database**
  - MongoDB version: 3.6.12
  - Storage engine:  WiredTiger
  - Hardware:    6 cores 16 GB  VPS
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): DigitalOcean

### Logs/Trace

I have near to zero experience with mongo, but some `db.currentOp` and `explain`s  led me to long running (1+ second)  queries involving  `session_token` , `_p_user`  from _Session collection and `_auth_data_anonymous.id` from _User.   I've indexed all of them and observed CPU usage dropped from 5x100% => 1*10% (cores) and latency is back to normal. 

Would be nice if someone experienced enough in mongo set up proper indices for these collections by default.

**Comment by mtrezza** [comment]
This relates to resource usage on MongoDB node instances, so the investigation should start on the MongoDB side to exclude the possibility that it is a MongoDB issue. If it turns out that there is a specific index missing that should be added by default, we can discuss adding it.

For now, I'm closing this as it does not seem to be a Parse Server issue.

For help with Parse Server, here are some resources you can try:
- For code-level questions we recommend Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-platform) tag.
- For network and server questions we recommend ServerFault using the [parse-server](https://serverfault.com/questions/tagged/parse-server) tag
- For questions that are not appropriate for the above mentioned sites we recommend our [community forum](https://community.parseplatform.org).

Feel free to comment if you have any questions and we can re-open this issue.
