### ISSUE TITLE
There is a bug if maxLogFiles suffer with d

### ISSUE THREAD

**Issue by beiguancyc** [parse-community/parse-server#6426]
Hello guys,

I test my app with config :
--appId xxx --masterKey xxx --databaseURI mongodb://xxx  --maxLogFiles  20
It's right.

but,if I write this like :
--appId xxx --masterKey xxx --databaseURI mongodb://xxx  --maxLogFiles  20d
It's wrong.

undefined:1
20d
  ^
SyntaxError: Unexpected token d in JSON at position 2

I find the code in follow file.

./lib/Options/parsers.js

function objectParser(opt) {
  if (typeof opt == 'object') {
    return opt;
  }
  return JSON.parse(opt);
}

I hope can  fix it,Thank you.

**Comment by dplewis** [comment]
Nice catch!

The issue is [here](https://github.com/parse-community/parse-server/blob/master/src/Options/Definitions.js#L237) it shouldn't use objectParser but one for number and strings.

**Comment by vivekjoshi556** [comment]
Hello @dplewis & @mtrezza,

According to documentation for maxLogFiles:

> This can be a number of files or number of days. If using days, add 'd' as the suffix.

I don't think 'd' matters here anyway because both imply the same thing.
For each day a new file is created, so how many log files should be created at max and how many days of files to keep is essentially the same thing, (so maybe we can update the documentation to remove instructions about this 'd')

**Comment by dplewis** [comment]
> For each day a new file is created

Up to 2 files can be created each day, one for `info` and `error`.

**Comment by vivekjoshi556** [comment]
Hi @dplewis,

Yes, I understand that 2 files are created. But my point was do we really need 'd' at all.

When you give:
- maxLogFiles = 2: It means that the maximum number of log files to keep is 2 (for each type info and err, i.e. a total of 4 files). Since, the new file is created on next day at the end we will have files with a rotation of 2 days.
- maxLogFiles = '2d': If we are using this, we are trying to do the same thing we are trying to delete files older than 2 days and keep logs for last 2 days (including today of-course).

Am I wrong about this?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-alpha.5](https://github.com/parse-community/parse-server/releases/tag/7.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.3.0](https://github.com/parse-community/parse-server/releases/tag/7.3.0)
