### ISSUE TITLE
I order my Parse Server with Created Date, All texts and Contents Are Arriving Properly, But the Image is not in Proper Order. Please Help Me.

### ISSUE THREAD

**Issue by companyofbala** [parse-community/parse-server#6571]
https://github.com/parse-community/parse-server/issues/6570#issue-595262729

**Comment by companyofbala** [comment]
Please help me out, I don't know Why is it closed?

**Comment by TomWFox** [comment]
Hi @companyofbala,

We ask people to fill out the issue template (the headings & questions in the issue body) as it provides the information we need in order to help.

I’m going to close this too, please open a new issue and use the bug template...
![IMG_0843](https://user-images.githubusercontent.com/13188249/78612318-f755a480-7860-11ea-9da9-7cc2beaa9dd7.jpeg)

You will then see all the headings and questions - please fill these out. The screenshot below shows a preview of an empty bug report issue...
![IMG_0844](https://user-images.githubusercontent.com/13188249/78612533-7c40be00-7861-11ea-901a-59679bbdcfdf.jpeg)

If you are still confused about what to do please continue the discussion here rather than opening further issues.
