### ISSUE TITLE
Using /sessions endpoint not creating restricted session tokens

### ISSUE THREAD

**Issue by stevestencil** [parse-community/parse-server#6612]
### Issue Description

When using the REST api to create a new session token as documented [here](http://docs.parseplatform.org/rest/guide/#creating-sessions) the tokens are not set as restricted.

### Steps to reproduce

Follow the instructions in the [REST API Guide](http://docs.parseplatform.org/rest/guide/#creating-sessions) to create a restricted session token
 
### Expected Results

A new session token should be created with restricted = true

### Actual Outcome

A new session token is created with restricted = false

### Versions

Parse-Server - 4.2.0
Parse-SDK-JS - 2.13.0

**Comment by EricNetsch** [comment]
@flovilmart @dplewis Yes, this is a major issue here among other related issues I will not disclose here

**Comment by EricNetsch** [comment]
@stevestencil Let us know which version of parse-server you are running?

**Comment by stevestencil** [comment]
@EricNetsch I updated my description with the versions

**Comment by davimacedo** [comment]
Hi guys. I've searched all the code base and also [this issue](https://github.com/parse-community/parse-server/issues/5047) and I believe that the restricted flag existed in parse.com but was never implemented in the Parse Server open source. It means that setting restricted to true or false has no effect. And that's why the guide steps are also not working. So, we have three options here:
1 - remove this feature from docs
2 - implement the feature
3 - 1, then 2

@dplewis @TomWFox @mtrezza thoughts?

**Comment by mtrezza** [comment]
This issue and the linked issue seem to be a vulnerability disclosure, should we redact it?

It makes sense to remove the feature of restricted sessions, because:

- From the docs I understand that restricted sessions is mainly a Parse IoT feature. The Parse Arduino SDK is retired and the Embedded C SDK shows limited activity, last relevant activity in 2016. There seem to be no active contributors nor experts for Parse IoT around. Some authors expressed [interest](https://github.com/parse-community/parse-embedded-sdks/pull/75#issue-129748976) in maintaining the SDK years ago, but it's questionable whether one maintainer would even be enough to keep it up-to-date. The danger with keeping this not-maintained SDK that is apparently not much in use either is what we are facing now: a fundamental security flaw that stays unnoticed for years.

- It seems to be a half-baked feature, because a restricted session can still read in User, Role and Session (except for unrestricted sessions), and can read/write data in any other class just like a normal session. Even the docs are somewhat contradictory:

> Restricted Sessions are useful for “Parse for IoT” devices (e.g Arduino or Embedded C) that may run in a less-trusted physical environment than mobile apps. However, please keep in mind that restricted sessions can still read data on User, Session, and Role classes, and can read/write data in any other class just like a normal session. So it is still important for IoT devices to be in a safe physical environment and ideally use encrypted storage to store the session token.

Use unrestricted sessions in a "less-trusted physical environment" but it's important to use them in a "safe physical environment" doesn't make any sense to me. The more effective approach seems to be to store tokens on the IoT device in a secure storage.

**Comment by davimacedo** [comment]
> This issue and the linked issue seem to be a vulnerability disclosure, should we redact it?

Technically yes, but, since the other issue is public for 2 years, I believe that it is better to keep it public for reference and we use this current thread to discuss the future of the feature.

**Comment by ggkitsas** [comment]
Hi,

I am contacting you on behalf of Snyk Security team. We would like to ask if you have a timeline for fixing this issue.

Best,
Snyk Security Team

**Comment by TomWFox** [comment]
I was just looking at this new [Snyk open source health report](https://snyk.io/advisor/npm-package/parse-server). Unfortunately we're being pulled down due to a couple outstanding vulnerabilities, this being one of them.

> So, we have three options here:
> 1 - remove this feature from docs
> 2 - implement the feature
> 3 - 1, then 2

I think we should remove the feature from the docs immediately, and then remove the feature from the codebase asap so we can close this one out.

**Comment by mtrezza** [comment]
I’m all for it!

**Comment by snoopysecurity** [comment]
hi, this issue has been fixed right? i see multiple PRs being referenced

**Comment by mtrezza** [comment]
The issue has not been fixed yet, it has merely been removed from the docs. Thanks for bringing this up.
Since this is a security issue, we should make a fix by removing this feature and backporting this to Parse Server 4.x.

@snoopysecurity Would you want to open a PR?

**Comment by mtrezza** [comment]
@snoopysecurity Thanks for bringing this up. I will look into this and whether this has been fixed or whether this is even an issue.

**Comment by mtrezza** [comment]
@snoopysecurity This has never been a vulnerability of this repository, the `restricted` session property is a mere code artifact of a feature that was never part of this repository. Parse Server has been open sourced from Parse.com in 2017; the feature was not part of the open source version, but the session property was not removed, apparently by mistake.

I went back to the initial Parse Server 2.0.0 release and it did not find any logic depending on the `restricted` field. The first PR that made a change and removed part of that code artifact was #4574. The rest of the artifact will be removed with https://github.com/parse-community/parse-server/pull/7543.

The Snky vulnerability [Improper Authorization](https://snyk.io/vuln/SNYK-JS-PARSESERVER-590116) can therefore be removed for *all* versions of this repository.

**Comment by TomWFox** [comment]
@ggkitsas Could you remove/resolve this vulnerability as per the explanation above?

**Comment by mtrezza** [comment]
I contacted Snyk about this; it seems that only Snky picked this up by mistake an added it to their internal list.

**Comment by benjifin** [comment]
Hey @mtrezza - thanks for the clarifications and sorry for the inconvenience, we (Snyk) will revoke this and that should take affect after tomorrow.

**Comment by mtrezza** [comment]
Thanks @benjifin, it seems that it should have been "deactivated" by setting the `versions <0.0.0`. However, it still appears for the parse-server 4.10.3 package as an active vulnerability:

![image](https://user-images.githubusercontent.com/5673677/132792342-a76357f5-d491-4741-954e-602961d2a1fe.png)

https://snyk.io/test/npm/parse-server/4.10.3

**Comment by benjifin** [comment]
This would look to be a caching issue of some sort of the package page -
but the data itself will not show up in any scan and even that link will
report back to the vulnerability page which has been updated accordingly:
https://snyk.io/vuln/SNYK-JS-PARSESERVER-590116.

The package pages and there data updates are not owned by our group, but
I'll drop a line in to the relevant team to ask them to see if they can
have a look at it so that it's removed faster :)

**Comment by mtrezza** [comment]
Closing, as the issue is not a bug.
