### ISSUE TITLE
why ParseDashboard can Scheduled Jobs ,but automatic execution scheduled tasks are not supported？

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/parse-server#6672]
sir
Q1:why ParseDashboard can Scheduled Jobs,but automatic  execution scheduled jobs are not supported?
    So what's the use of  scheduled jobs here? just have a look?
or is my  scheduled jobsconfigured incorrectly? But I did it manually success。
![QQ截图20200507020306](https://user-images.githubusercontent.com/52989321/81211991-c6ef5a80-9006-11ea-9480-d77196a8e3c7.png)

Q2:In addition, may i ask a question, if you let the parse dashboard not use UTC time zone，
Q3:where can find all the parse-server config options? I can find it in the document before. Can you give me a link （）

**Comment by mtrezza** [comment]
- Q1: Scheduling a job in Parse Dashboard creates a database entry in the `_JobSchedule` collection. As the docs say, you would need an external process that queries this collection and run the jobs according to the schedule intervals.

- Q2: I don't understand your question.

- Q3: See [here](https://github.com/parse-community/parse-server#configuration) and [here](http://parseplatform.org/parse-server/api/master/ParseServerOptions.html).

**Comment by lybaiyy123** [comment]
> * Q1: Scheduling a job in Parse Dashboard creates a database entry in the `_JobSchedule` collection. As the docs say, you would need an external process that queries this collection and runs the jobs accordingly.
> * Q2: I don't understand your question.
> * Q3: See [here](https://github.com/parse-community/parse-server#configuration) and [here](http://parseplatform.org/parse-server/api/master/ParseServerOptions.html).

thanks，
Q1 Do you have any examples...

**Comment by mtrezza** [comment]
Thanks for your question.

It really depends on your architecture what makes most sense to you. A quick Google search should give you some hints. Some threads as starting point:

- https://stackoverflow.com/questions/39217677/how-is-everyone-going-about-implementing-scheduled-jobs-cloud-jobs-on-parse-se
- https://github.com/parse-community/parse-server/pull/3927

Since this is not an issue with Parse Server, detailed questions regarding your implementation are better suited on Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-server) tag. If your question is not appropriate for the site please use our [community forum](https://community.parseplatform.org).

**Comment by lybaiyy123** [comment]
> Thanks for your question.
> 
> It really depends on your architecture what makes most sense to you. A quick Google search should give you some hints. Some threads as starting point:
> 
> * https://stackoverflow.com/questions/39217677/how-is-everyone-going-about-implementing-scheduled-jobs-cloud-jobs-on-parse-se
> * #3927
> 
> Since this is not an issue with Parse Server, detailed questions regarding your implementation are better suited on Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-server) tag. If your question is not appropriate for the site please use our [community forum](https://community.parseplatform.org).

thank you very much

**Comment by mtrezza** [comment]
I assume the issue can be closed then?
