### ISSUE TITLE
How to send metadata when using restful api to upload a image?

### ISSUE THREAD

**Issue by smoothdvd** [parse-community/parse-server#6771]
curl -X POST \
  -H "X-Parse-Application-Id: foo" \
  -H "X-Parse-REST-API-Key: bar" \
  -H "Content-Type: application/json" \
  --data-binary '@src/assets/test.png' \
  http://localhost:1337/parse/files/test.png

How to send  metadata with this post request?

Like in JS SDK, we can do this by
```
const file = new Parse.File('myfile.zzz', fileData, 'image/png', metadata, tags);
```

**Comment by mtrezza** [comment]
You would set it in the `Content-Type` header.

See the examples in the [docs](https://docs.parseplatform.org/rest/guide/#uploading-files) where different content types are used.

**Comment by smoothdvd** [comment]
@mtrezza docs not mentioned how to send metadata or tags.

**Comment by mtrezza** [comment]
Did you try to set a request body like this:

```
fileData: {
    metadata: { ... },
    tags: { ... }
}
```

That is what happens in the [Parse JS SDK]( https://github.com/parse-community/Parse-SDK-JS/blob/393b7233f657fe1fc3456650e7902dc059204bf7/src/ParseFile.js#L458-L460).

**Comment by smoothdvd** [comment]
@mtrezza Yes, this is the  "hack" way I used in my code.

```
curl -X POST
-H "Accept: application/json"
-H "Content-Type': text/plain"
-d '{"base64": "xyz", "fileData":{"metadata":{"foo":"bar"}, "tags":{}}, "_ContentType": "type", "_ApplicationId": "id", "_ClientVersion": "client"}
```

**Comment by mtrezza** [comment]
Glad to see it works. This is the correct way to do it, it is just not documented, well spotted!

Would you want to add this to the documentation and open a PR?

**Comment by smoothdvd** [comment]
@mtrezza Let me test it with move _ApplicationId from json body to header. And I also want upload  file with multipart/form-data instead of base 64.

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.

Docs issue in parse-community/docs#749

**Comment by evtimDev** [comment]
One important caveat for this working is one should not add the applicationId in the header, because otherwise the json parsing of the body will be skipped:

https://github.com/parse-community/parse-server/blob/fe02d3e8aa875f362377cc877a65831b010b00a6/src/middlewares.js#L79-L93

**Comment by mtrezza** [comment]
@evtimDev Do you think the documentation could be improved?

**Comment by evtimDev** [comment]
Hi @mtrezza! Yes, improved documentation for the REST API would be useful, I also noted it in the doc issue you created, just wanted to make sure it's captured and recorded. 

I stumbled upon this issue as I wanted to send metadata & tags on file upload from the Android SDK (not supported there) so I had to roll-out a REST API solution for the Android. It is a useful feature, as it can simplify bookkeepings and also save on the additional request to associate a file with a object when the association is implemented in cloud code, on file after save, using the metadata/tags. 

Since this is supported by JS SDK as well as the REST API, it makes sense to roll-out the capability to all platform SDKs.  

In looking at the server code, it looks like this was some sort of special-case handling?  I wonder if a more consistent approach would be for the server to receive the metadata and tags via headers instead - this will save trying to parse and validate the body as a json. I haven't looked at what changes would be needed on the client SDK side to support this in the iOS/Android SDKs.

Should I open new issues to investigate these? I'm thinking one issue per client SDK that does not support file upload with metadata/tags yet, plus one issue for server to support receiving these via headers, does that make sense?

**Comment by mtrezza** [comment]
It probably makes more sense to open a feature request in the specific SDK(s) where you have an actual need for your project. For the simple reason that there is currently low feature parity across SDKs - something we are currently looking into. 
If you have a suggestion for what to add to the docs, please feel free to open a PR with a suggestion, since the issue already exists. We'll be happy to review.

**Comment by evtimDev** [comment]
OK, I generalized and opened the following feature requests:

https://github.com/parse-community/Parse-SDK-Android/issues/1201
https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1766
https://github.com/parse-community/parse-server/issues/8796

It looks like the metadata/tags are sort of meant to be persisted together with the file (I haven't done extensive read up on the metadata/tags and what storage adapters support persisting those and the cases they correctly round-trip back to the client), it is a bit of a different use-case from what I was looking for - I just want some parameters together with the file POST request (probably best via a header). 

Considering this, I think we should first evaluate these future requests instead of adding documentation to the REST API at this point.  I think the comments in this bug are already a de-facto documentation of how to achieve metadata/tags via REST API for parity to the way JS SDK does this.
