### ISSUE TITLE
Is parse-server dead for real?

### ISSUE THREAD

**Issue by UltimateYZ** [parse-community/parse-server#6814]
Hello parse-server devs,
I wanted to know if parse-server is dead for real, like it doesn't host nothing any more... Or those cool cloud features are still working?

**Comment by TomWFox** [comment]
Parse.com has shut down (the hosted service) was shut down years ago. Parse Server is the self-hosted replacement developed by some of the original Parse developers and since then the open spice community.

Many of the cool cloud features exist in Parse Server (as well as a bunch of newer features), the difference is that you now need to self-host an instance of Parse Server on your own computer of a cloud provider like AWS, Heroku.

If you don’t want to self-host Back4App.com and Sashido.io offer turn-key Parse Server solutions.
