### ISSUE TITLE
Apple sign in client_id typo

### ISSUE THREAD

**Issue by ChrisEelmaa** [parse-community/parse-server#6858]
In documentation https://docs.parseplatform.org/parse-server/guide/#apple-authdata it is mentioning that you can use client_id. That might have been true in the past, but now the correct way is to use clientId.

**Comment by mtrezza** [comment]
Thanks for reporting. This may be an issue with the docs and therefore belong to the [docs repository](https://github.com/parse-community/docs), however before we transfer this, I want to take a closer look at the apple auth adapter.

The test cases seem to use both `clientId` and `client_id` as parameters:

https://github.com/parse-community/parse-server/blob/4cec333cf96eb10f836a83932797daba57a07144/spec/AuthenticationAdapters.spec.js#L1238
https://github.com/parse-community/parse-server/blob/4cec333cf96eb10f836a83932797daba57a07144/spec/AuthenticationAdapters.spec.js#L1247

@drdaz Since you worked on Sign-in with Apple on iOS recently, do you have any insight into the Apple auth adapter and why we have two different parameters in the test cases?

**Comment by drdaz** [comment]
> @drdaz Since you worked on Sign-in with Apple on iOS recently, do you have any insight into the Apple auth adapter and why we have two different parameters in the test cases?

I can't say that I do. But I took a look at the API history for the client config: https://developer.apple.com/documentation/sign_in_with_apple/clientconfigi?changes=latest_minor

The clientId name appears to have been consistent across releases.

**Comment by drdaz** [comment]
@UnderratedDev As the committer, can you comment on this?

**Comment by drdaz** [comment]
I've been sniffing around the history for the Apple auth adapter, and it looks like we did use the client_id name internally in earlier revisions. Looks like we tried to stop doing that here https://github.com/parse-community/parse-server/commit/8e0e485de1649993f9fe46da6894bb960d92cbe1#diff-9c3309b0860c37781a13147586659761.

**Comment by UnderratedDev** [comment]
There isn't one particular reason to change from client_id to clientId. Mainly it was to be consistent with the rest of the code, for instance, we use keyId, verifyIdToken. Most of the code uses the camel case javascript style. We should be using just clientId. 

Those tests also need to be reworked as we don't have any parse credentials for apple. We have to input our own & generate our own tokens manually with a separate application.

Also, side note, I made a pr for p8 file support for apple sign but it needs better testing (I don't wish to put in my p8 file or personal credentials). If anyone could help, that would be appreciated. #6648 Hope that clears it all up.

**Comment by mtrezza** [comment]
I think there are some aspects to distinguish:
- the Parse Server internal parameter syntax
- the key name that is transmitted to Apple's auth endpoint to verify a token

The authentication can be done in different ways:
- for the Apple Web Service Endpoint (REST API) the key name is [client_id](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens)
- for the Apple Sign in JS Framework it is [clientId](https://developer.apple.com/documentation/sign_in_with_apple/clientconfigi).

It seems we are using neither directly, instead we use the JWT framework (which uses the Apple Web Service Endpoint) which has an `audience` parameter for which the value of the Parse Server auth adapter configuration `clientId` key is set:

https://github.com/parse-community/parse-server/blob/dd2b64ef65674ffc2e59c8a106b5e71bcb29455c/src/Adapters/Auth/apple.js#L71-L75

My conclusion would be:
- @ChrisEelmaa is correct in that the docs need to updated to use `clientId` instead of `client_id`, because this has been missed in the docs during the syntax refactoring in https://github.com/parse-community/parse-server/commit/8e0e485de1649993f9fe46da6894bb960d92cbe1 that @drdaz pointed out --> @ChrisEelmaa can you please open a new issue in the [docs repository](https://github.com/parse-community/docs)? Instead of transferring this issue to the docs, I would rather keep it here because the discussion became more Parse Server auth adapter centric.
- the syntax refactoring in https://github.com/parse-community/parse-server/commit/8e0e485de1649993f9fe46da6894bb960d92cbe1 missed several parameters in the test cases for the Apple auth, that should be refactored for consistency --> requires a PR assigned to this issue

**Comment by UnderratedDev** [comment]
@mtrezza yep, I do remember using the Apple Sign in JS Framework & they do use clientId. Good catch!

**Comment by drdaz** [comment]
Yes... conclusion checks out.

And perhaps make the tests use consistent syntax, lest we find ourselves asking the same question at some point in the future.

**Comment by mtrezza** [comment]
Reopening as https://github.com/parse-community/docs/issues/761 is not solved.
