### ISSUE TITLE
Inconsistency between afterLiveQueryEvent "type" and SDK

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7022]
**Is your feature request related to a problem? Please describe.**

This is my fault, but basically, request.event in the `afterLiveQueryEvent` contains a first letter uppercase, where the JS SDK does not. E.g:

```
 Parse.Cloud.afterLiveQueryEvent('TestObject', req => {
      expect(req.event).toBe('Create');
});
```

vs

```
subscription.on('create', object => {});
```

This could be confusing and potentially lead to bugs. Infact, I even made the mistake for the docs:

```
Parse.Cloud.afterLiveQueryEvent('MyObject', async (request) => {
  if (request.event != "update") {
    request.sendEvent = false;
    return;
  }
  const object = request.object;
  const pointer = object.get("child");
  await pointer.fetch();
});
```

This example will never fire as .event is defined as:

```
let type;
if (isOriginalMatched && isCurrentMatched) {
   type = 'Update'; // 'Update', not 'update'
} else if (isOriginalMatched && !isCurrentMatched) {
   type = 'Leave';
} else if (!isOriginalMatched && isCurrentMatched) {
   if (originalParseObject) {
      type = 'Enter';
   } else {
      type = 'Create';
   }
} else {
   return null;
}
```

**Describe the solution you'd like**

Casing consistent across SDK and afterLiveQueryEvent, or at least documented that they are different.

**Comment by mtrezza** [comment]
Thanks for reporting.

I classified this as a bug with severity level 4 because:
- this is an inconsistency with expectations that can be derived from related syntax in the Parse JS SDK
- this is an inconsistency with the docs
- the functionality itself is not impaired, albeit one would have to look into the source code to find the correct event spellings

The suggested solution would be to make the spelling consistent by changing it to lower case.
The bug was apparently introduced in https://github.com/parse-community/parse-server/pull/6859, https://github.com/parse-community/docs/pull/773.



Would you be willing to open a PR?
We should also look at test cases that verify the correct spelling.

**Comment by dblythy** [comment]
Agree with all the points you've raised. Only a minor nit that will cause inconvenience and confusion. Potentially breaking change for the next release though for those already utilising the trigger.

**Comment by mtrezza** [comment]
Yes, given that this feature has only been introduced about 1 month ago, I would assume that the breaking change impact is not that big of a deal.
