### ISSUE TITLE
Add API mail adapter to docs

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#7125]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Feature / Enhancement Description
Add [API Mail adapter](https://www.npmjs.com/package/parse-server-api-mail-adapter) to list of mail adapters in docs.

- The main issue this adapter solves are localized, templated emails for password reset and email verification.
- Adapter allows to modify the form links to attach the user locale, which allows also the forms to be localized or pass any other arguments to customize the form.

**Comment by TomWFox** [comment]
You could add this to the [community section on the website](https://parseplatform.org/#community).

**Comment by mtrezza** [comment]
It would be the only email adapter on there, is that because we just didn't add any other email adapters yet?

**Comment by TomWFox** [comment]
I think the section has just been neglected, there is a My SQL adapter

on there. You could wait until we have a new page for it and then we
could add all of the adapters.

On January 15, 2021, GitHub <notifications@github.com> wrote:
> It would be the only email adapter on there, is that because we just

> didn't add any other email adapters yet?
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/parse-community/parse-
server/issues/7125#issuecomment-760639708>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ADETZGNITIQRJJYDQNX6AG3SZ7A6DANCNFSM4WB4S4PQ>.

**Comment by mtrezza** [comment]
I'll wait for the new page then

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
