### ISSUE TITLE
Improve transparency of reset password flow

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7434]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

As discussed [here](https://github.com/parse-community/parse-server/security/advisories/GHSA-cfgm-jqhh-xmhr#advisory-comment-64808), password reset should throw with an invalid email, rather than returning success.

### Steps to reproduce

Request a password reset with an invalid email.

### Actual Outcome

Response is success.

### Expected Outcome

Response should be "invalid email" or something useful.

### Failing Test Case / Pull Request

- [x] 🤩 I submitted a PR with a fix and a test case.
- [x] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `master` (4.5.0)

**Comment by mtrezza** [comment]
Thanks for opening this issue.

As described in your references discussion, this change makes sense to give the developer more control over the password reset flow.

The security implication is marginal because it allows to determine whether a specific email address is assigned to a user, but that is also possible via the sign-up endpoint.

However, since obfuscation is also a security strategy, there is a security implication which has to be considered and mentioned in the changelog as a significant change. 

In addition, it is a breaking change if instead of success an error response is returned in some cases. According to our deprecation policy this change should be phased in.

**Comment by dblythy** [comment]
Ok. Sounds good. How should we go about depreciating it? Add a warning and then remove it at a later date?

**Comment by mtrezza** [comment]
We would add a new parse server option where the developer can choose whether the endpoint should return an error or success if the email doesn't exist.

The default would be to return success (as it currently does), with a deprecation log if the option is not manually set return an error.

Instead of deprecating we could also make it a permanent option, without deprecation. So we keep the obfuscating default setting to return success. If a developer wants to build a custom flow, they can choose to set it so return an error.

**Comment by dblythy** [comment]
Right, so rather than deprecating the current flow, we could add a `passwordPolicy.validateEmails` option or something, that defaults to false?

**Comment by mtrezza** [comment]
Yes, what do you think?

**Comment by dblythy** [comment]
Sounds like an elegant solution. Thanks for the discussion! I'll work on it.

**Comment by mtrezza** [comment]
I've removed this from Parse Server 6 release list as it's not a breaking change anymore, see https://github.com/parse-community/parse-server/pull/7551#pullrequestreview-1248757874.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.34](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.34)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-server/releases/tag/6.1.0)
