### ISSUE TITLE
Depreciate `Parse.Cloud.httpRequest`

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#7589]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Our docs state:

> You can use your favorite npm module to make HTTP requests, such as request. Parse Server also supports Parse.Cloud.httpRequest for legacy reasons

Why should we continue to support a legacy HTTP module, which hasn't been updated in 3 years, where there are more popular solutions that constantly update their security issues and vulnerabilities?

The http module also uses deprecated methods, such as `querystring` and `parse`.

Also `request` is archived, so we shouldn't recommend that either.

We've seen Parse.Cloud.httpRequest be the source of [many issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue+httpRequest)

### Feature / Enhancement Description

Migrate to a dedicated HTTP library, such as axios

### Example Use Case

Log `Parse.Cloud.httpRequest is depreciated. Please migrate to different HTTP request solution`

### Alternatives / Workarounds

- Keep the legacy library as is.
- Set Parse.Cloud.httpRequest as an alias to `axios`.

**Comment by dblythy** [comment]
Related: #6361, #7232

**Comment by mtrezza** [comment]
Do we even need to offer `Parse.Cloud.httpRequest`? Any dev can (and maybe already does) choose their own library depending on its capabilities. What is the benefit for devs in having this method?

**Comment by dblythy** [comment]
I would say there is no real reason why we should offer it. Perhaps we should remove it entirely from V5 as a breaking change?

**Comment by uzaysan** [comment]
httpRequest has issues. Sometimes request fails or constructed in worng way and server returns 4XX response. Axios works fine. I think we should remove it.

**Comment by mtrezza** [comment]
If it is already severely broken in the way that you describe, where requests sometimes fail, we probably should make a small change to use axios, even while it's being deprecated. Because deprecation means it will still be available for a year.

**Comment by uzaysan** [comment]
> If it is already severely broken in the way that you describe, where requests sometimes fail, we probably should make a small change to use axios, even while it's being deprecated. Because deprecation means it will still be available for a year. Not sure how broken it is though.

On the back4app support group on slack someone faced this problem. Syntax was correct but server wasn't returning the response it should.  İ suggested him to use node-fetch or axios to see if problem is under default httpRequest and he said problem is fixed when using axios. And like you said, one can easily add their preferred http library. Maintaining a default one should be avoided in my opinion.

**Comment by mtrezza** [comment]
I see. I think we have 3 options:
- a) Remove it immediately with Parse Server 5, which will break many deployments for which http currently works fine (I understand it only has issues with specific requests?)
- b) Deprecate it in v5 and remove it in v6
- c) Same as (b) and also replace the http library with axios to avoid a breaking change

Which would you prefer?

**Comment by uzaysan** [comment]
I think option b makes sense. Option c is also possible but imo there is no point of fixing a bug of a deprecated feature.

**Comment by dblythy** [comment]
I would like to see it, and `Parse.Cloud.useMasterKey()` removed completely, but I understand how our community has responded to breaking changes in the past. If you are currently using it for simple requests, it’s probably working fine and having to migrate straight away could be frustrating. 

I think option b is the best, we could go with c but I think having direct aliases to other packages could result in developers assuming issues and documentation related with `Parse.Cloud.httpRequest` are our responsibility, rather than axios’.

**Comment by mtrezza** [comment]
I think we agree on (b) then, sounds good to me.

**Comment by mtrezza** [comment]
Closing via #7595

**Comment by mtrezza** [comment]
Reopened to discuss:

@dblythy I just noticed that `httpRequest` is still used internally for hooks in `HooksController.js`, even if we do not expose it via `Parse.Cloud.httpRequest`. So the original issue of the deprecated legacy module is not solved by only removed public accessibility. That means (a) is not really an option, and we'd have to do (c) in some form I suppose. In any case, I still think deprecating the public method in #7595 made sense.

**Comment by mtrezza** [comment]
I've renamed the title and objective of this issue to replace the outdated http request dependency with axios. You gave [many good reasons](https://github.com/parse-community/parse-server/issues/7589#issue-1003845237) why we should replace it. We have already deprecated it in https://github.com/parse-community/parse-server/pull/7595 and will remove its exposure in https://github.com/parse-community/parse-server/issues/8271. It seems that we still need to replace it, since it's also [used internally](https://github.com/parse-community/parse-server/issues/7589#issuecomment-946954998).

**Comment by mtrezza** [comment]
Node 18 provides a native method [fetch](https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental) that should make it unnecessary to add a dependency for http requests. Parse Server 7 will support Node >=18 (Node 16 EOL will be Sept 2023), and from then on we can switch to native `fetch`.

More than 500 CI tests are currently using the request lib. Migrating to axios and possibly introducing bugs or flaky tests doesn't seem a necessary effort. Even though the request lib is outdated, the issues reported by developers were when using the `Parse.Cloud.httpRequest` method, which will be [removed](https://github.com/parse-community/parse-server/issues/8271) anyway. Parse Server internally and the tests seem to work fine with the request lib. So we won't touch it for now.

From Parse Server 7 (2024) onwards, we can migrate to the native `fetch` method. Since it will be only internal, it won't be breaking and we can migrate gradually. Until then, this issue is on hold.

**Comment by ardatan** [comment]
Maybe you can try `@whatwg-node/fetch`  (GraphQL Yoga uses it under the hood) which ponyfills Fetch API only if it doesn't exist in the environment.
https://github.com/ardatan/whatwg-node/tree/master/packages/fetch

I'd love to help you with this if you decide to give it a try.

**Comment by Urigo** [comment]
@ardatan I'm also linking the blog post you wrote about it: https://the-guild.dev/blog/fetch-for-servers

**Comment by mtrezza** [comment]
I'm skeptical given the amount of changes we'd have to make throughout the repo and that only to bridge 2023. Unless there is another benefit?

**Comment by Urigo** [comment]
@mtrezza we are not sure it would be a big effort, are you open for us trying out and see if we can come up with a PR for it before Parse 6?
