### ISSUE TITLE
Add a log id to identify all logs that were generated when handling a specific request/response

### ISSUE THREAD

**Issue by xeoshow** [parse-community/parse-server#7668]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Feature / Enhancement Description

Add a log id or something like that, passed through the whole life cycle for a request → functions → reponse, so if some user got problem, we could use the log id to filter only the related info out of the log files.

**Comment by mtrezza** [comment]
Do you have any conceptual suggestion? I wonder whether such a feature should be part of Parse Server, because a request begins as soon as it reaches your infrastructure public gateway, and that's way before Parse Server. The request may even never reach Parse Server, but the client still gets a response. The usual approach is to assign a request ID early in your infrastructure, ideally already at the gateway. If you want to start even earlier, you can add a UUID on the client side and send it as part of the request, so you have it even at the client side and the user can tell you the request ID for you to troubleshoot. You could look into the Idempotency feature of Parse Server, which makes the client SDK send a UUID with a request, maybe you can repurpose that for logging. Mind the data overhead in any approach though. You can output such an ID in a custom Parse Server log adapter I suppose.

**Comment by xeoshow** [comment]
@mtrezza Thanks for reply!
It is just originated from this community post and is recommeded open an issue:
https://community.parseplatform.org/t/config-logger-system-for-parse-server/2124/7

**Comment by mtrezza** [comment]
Thanks for opening this issue. We use GitHub for issues that are already beyond a discussion whether or not they make sense. I’m moving the discussion from the GitHub issue back into the forum, because I think this still requires some more abstract deliberation.

Sorry for the ping-pong, and thanks again for opening the issue here. We can re-open this issue once there is consensus on whether and how such a feature should be implemented - if at all.

**Comment by Rajon9** [comment]
@xeoshow 
I need your help. Can we sit down and talk? You won't be disappointed
Thank you.
