### ISSUE TITLE
Role lookup should use index

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8291]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

An index is created when roles are created, however there is no hint to the role name passed to the database

https://github.com/parse-community/parse-server/blob/199dfc17226d85a78ab85f24362cce740f4ada39/src/Auth.js#L161-L181

### Steps to reproduce

Create a role

### Actual Outcome

Role index is not used to lookup user roles

### Expected Outcome

Hint should be used

### Environment

Server
- Parse Server version: `5.3.0`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `5.3.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `js`
- SDK version: `3.5.0`

**Comment by mtrezza** [comment]
Why would there need to be a hint?

**Comment by dblythy** [comment]
Doesn’t mongo use the `id` index by default? Or would it automatically use the name index

**Comment by mtrezza** [comment]
The MongoDB query planner should automatically choose the most appropriate index. If there are multiple possible indices (e.g. compound index or complex query), it tries out a couple of variations and should choose the best performing index. Unless an index is forced with `hint`. The QP algorithm can be complex, so to really know which index has been used you would look at the historic MongoDB logs. Alternatively, to get a pretty good indication of which index will be used, you could use an `explain`.

**Comment by Moumouls** [comment]
Hi @mtrezza @dblythy 

A note here, `roles` and `users` is a relational field on `_Role` class. Parse Server has an index on `name` but currently Parse Server DOES NOT create at all indexes for _Join classes.

An issue was opened: https://github.com/parse-community/parse-server/issues/7832 about that Parse SHOULD automatically create indexes on Join classes to improve performance.


Here, for example, is a workaround code that I've on my side to create Join indexes at startup.


```ts
const joinIndex = [{ relatedId: 1 }, { owningId: 1 }] as [
	{ relatedId: 1 },
	{ owningId: 1 },
]

const indexes = {
	'_Join:users:_Role': joinIndex,
	'_Join:roles:_Role': joinIndex,
	'_Join:docSignatures:Urn': joinIndex,
}

export const ensureAdditionalIndexes = async () => {
	const config = await Parse.Config.get({ useMasterKey: true })
	if (config.get('indexesInitialized')) return

	const { db } = await getMongoClient()
	const results = await Promise.allSettled(
		Object.entries(indexes).map(async ([className, idx]) => {
			const collection = db.collection(className)
			await Promise.all(idx.map((index) => collection.createIndex(index)))
		}),
	)

	if (results.every((r) => r.status === 'fulfilled')) {
		await Parse.Config.save(
			{ indexesInitialized: true },
			{ indexesInitialized: true },
		)
	}
}
```

Another note, in my company we are now using MongoDB Serverless for our deployments (i've some PRs open about this). It works really well, but it's REALLY important to have indexes created correctly, otherwise, a collection scan is performed at each query and the Mongo Serverless costs will explode.

I think https://github.com/parse-community/parse-server/issues/7832 is the correct way to fix this issue if i understand it correctly !

**Comment by Moumouls** [comment]
Hi @mtrezza @dblythy 

A note here, `roles` and `users` is a relational field on `_Role` class. Parse Server has an index on `name` but currently Parse Server DOES NOT create at all indexes for _Join classes.

An issue was opened: https://github.com/parse-community/parse-server/issues/7832 about that Parse SHOULD automatically create indexes on Join classes to improve performance.


Here, for example, is a workaround code that I've on my side to create Join indexes at startup.


```ts
const joinIndex = [{ relatedId: 1 }, { owningId: 1 }] as [
	{ relatedId: 1 },
	{ owningId: 1 },
]

const indexes = {
	'_Join:users:_Role': joinIndex,
	'_Join:roles:_Role': joinIndex,
}

export const ensureAdditionalIndexes = async () => {
	const config = await Parse.Config.get({ useMasterKey: true })
	if (config.get('indexesInitialized')) return

	const { db } = await getMongoClient()
	const results = await Promise.allSettled(
		Object.entries(indexes).map(async ([className, idx]) => {
			const collection = db.collection(className)
			await Promise.all(idx.map((index) => collection.createIndex(index)))
		}),
	)

	if (results.every((r) => r.status === 'fulfilled')) {
		await Parse.Config.save(
			{ indexesInitialized: true },
			{ indexesInitialized: true },
		)
	}
}
```

Another note, in my company we are now using MongoDB Serverless for our deployments (i've some PRs open about this). It works really well, but it's REALLY important to have indexes created correctly, otherwise, a collection scan is performed at each query and the Mongo Serverless costs will explode.

I think https://github.com/parse-community/parse-server/issues/7832 is the correct way to fix this issue if i understand it correctly !

**Comment by mtrezza** [comment]
Closing; to summarize: `hint` is not necessary; if indices exist it will be automatically chosen. However, index only exists if developer creates it, so https://github.com/parse-community/parse-server/issues/7832 should create it automatically. If that's incorrect please comment and we can reopen.
