### ISSUE TITLE
Migration (2.x->3.x server) doc misses a comment in final example

### ISSUE THREAD

**Issue by richardgroves** [parse-community/parse-server#8401]
### New Issue Checklist

- [ x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
The migration from 2.x to 3.x documentation doesn't mention "// after with async/await" in the final example on page https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md

### Steps to reproduce
Read the page and note the missing single line in the final example

### Actual Outcome
N/A

### Expected Outcome
N/A
### Environment
N/A

Server
- Parse Server version: `N/A`
- Operating system: `N/A`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Reading docs`

Database
- System (MongoDB or Postgres): `N/A`
- Database version: `N/A`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `N/A`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `N/A`
- SDK version: `N/A`

### Logs
N/A

**Comment by richardgroves** [comment]
NB: Sorry for the silliness of the issue but the one line doc fix PR *requires* an issue to be opened before it can be submitted. Wish I'd never bothered now.

**Comment by mtrezza** [comment]
Parse Server 3 is not supported anymore, so I guess it makes sense to remove that document altogether.

**Comment by richardgroves** [comment]
> Parse Server 3 is not supported anymore, so I guess it makes sense to remove that document altogether.

Eek! I've got a project I'm migrating from 2.X and it seems a step to a 3.X version before a leap up to 4 or 5 makes sense. Not much cloud code (~2k lines) but old and messy and hard to test. I'll see what the latest docs offer in terms of help.

**Comment by mtrezza** [comment]
You can always go back to the LTS branch of a previous version to find the previously relevant documents. For example you could take a look at the branches [release-4.x.x](https://github.com/parse-community/parse-server/tree/release-4.x.x) and [release-5.x.x](https://github.com/parse-community/parse-server/tree/release-5.x.x). LTS branches are a recent concept, so there is no branch for Parse Server 2 or 3.

In terms of migrating, the biggest change occurred from 2 to 3. Once you're on 3, it should be much easier to migrate to 4, 5 and eventually 6. I should note that our breaking change policy, deprecation policy and semver are more strictly followed since 4, so once you're there it should go smoothly.

If you need any help, please don't hesitate to reach out to the community via our [community forum](https://community.parseplatform.org) or our [community chat](https://chat.parseplatform.org).
