### ISSUE TITLE
Rate limit feature is incompatible with Node 14

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8577]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When updating #8558, I assumed the Node 14 failure was flaky. It was not.

The code uses String.replaceAll, which is available in Node 15+

### Environment

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by mtrezza** [comment]
That's the unfortunate effect of flaky tests. They are so frequent (although much has improved in the past year) that a failing test easily gets mistaken for being flaky. I think as a new rule we'll re-run the CI until all tests pass before merging a PR. I think that can be set as required in the repo setting so that also reviewers and maintainers cannot skip that.

Maybe we can find a Node compat check for the CI that explicitly check for commands that require a higher Node version than the min package version.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.13](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
