### ISSUE TITLE
Default fileExtension regex does not match `plain` files.

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-server#8698]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

The current default `fileExtension` regex (`"^[^hH][^tT][^mM][^lL]?$"`) does not match `plain`.

### Steps to reproduce

1. Do not set fileExtension
2. Try to create file

### Actual Outcome

Error

### Expected Outcome

Should succeed

### Environment

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `FILL_THIS_OUT`
- SDK version: `FILL_THIS_OUT`

**Comment by dblythy** [comment]
Related: https://github.com/parse-community/Parse-SDK-JS/issues/1979

**Comment by dblythy** [comment]
I think the default regex should instead be `'^(?!html$|htm$).*'`

**Comment by mtrezza** [comment]
From the web server point of view, the path component of a URI is case sensitive, so we cannot add the `i` flag to the regex. On the other hand modern web browsers handle file extensions case-insensitive (`file.HTML`, `file.html`, `file.HtMl`, etc. are all rendered as HTML).

So to truly prevent HTML content files we'd need to block any case-style without using the `i` flag, that's why we had the regex so far.

If we don't keep the current case insensitive regex style, then the regex could be simply `^(?!html?$)`. This requires only 4 steps for the regex engine, regardless of the extension string length. But that would allow uploading `malicious.HTmL` and browsers would likely render the HTML content.

If we want to keep the case insensitive style then we could use `^(?!(h|H)(t|T)(m|M)(l|L)?$)`, which should
- not match `html`, `htm` with any casing combination (e.g. `html`, `HTML` `HtMl`)
- match empty string `''`, i.e. no file extension
- match any other extension

Btw, the current file extension regex looks wrong anyway as it won't allow extensions shorter than 3 or longer than 4 chars.

**Comment by dblythy** [comment]
Is it possible that a file could be uploaded with the extension `hTmL`?

**Comment by mtrezza** [comment]
If the file extension regex is `["^(?!html?$)"]` without the `i` flag, then yes, and a browser would render it. But we can't use the `i` flag, because we would limit developers who differentiate casing in the URI, technically `index.HTML` and `index.html` could be 2 different files. So we'd need `^(?!(h|H)(t|T)(m|M)(l|L)?$)`.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.26](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.26)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
